cyverse/troposphere

troposphere/templates/application.html
troposphere/urls.py
troposphere/views.py

* Adds the emulated users token to the template (when emulating)
* Fix to correctly remove the emulated user

Intercom fix

---

troposphere/models.py
troposphere/views.py

Adds initial support for an application wide maintenance page
* Redirects all users to the admin page (including admins).
* Requires a proxy pass in apache to the maintenance page

Maintenance fix

---

troposphere/static/css/app/app.scss
troposphere/static/css/app/applications.scss
troposphere/static/css/app/global.scss
troposphere/static/css/app/header.scss
troposphere/static/css/app/layout.scss
troposphere/static/css/app/provider.scss

1. Uses variables for colors to support theming.

Support themes

---

troposphere/settings/default.py
troposphere/static/js/actions/InstanceActions.js
troposphere/static/js/actions/TagActions.js
troposphere/static/js/bootstrapper.js
troposphere/static/js/components/MaintenanceMessageBanner.react.js
troposphere/static/js/components/SplashScreen.react.js
troposphere/static/js/components/applications/detail/versions/Machine.react.js
troposphere/static/js/components/applications/detail/versions/MachineList.react.js
troposphere/static/js/components/applications/detail/versions/VersionsView.react.js
troposphere/static/js/components/modals/instance/InstanceLaunchModal.react.js
troposphere/static/js/components/modals/instance_launch/MachineSelect.react.js
troposphere/static/js/components/modals/project/instance_launch/InstanceLaunch.react.js
troposphere/static/js/components/projects/detail/resources/ButtonBar.react.js
troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js
troposphere/static/js/components/projects/detail/resources/ResourceActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/VolumeActionButtons.react.js
troposphere/static/js/models/Machine.js
troposphere/static/js/stores/VolumeStore.js

Addresses the following JIRA issues:
https://pods.iplantcollaborative.org/jira/browse/ATMO-717
https://pods.iplantcollaborative.org/jira/browse/ATMO-720
https://pods.iplantcollaborative.org/jira/browse/ATMO-725
https://pods.iplantcollaborative.org/jira/browse/ATMO-730
https://pods.iplantcollaborative.org/jira/browse/ATMO-731
Also adds the following feature:
The main Instance and Volumes actions are now accessible from the button bar on the project resources.  You no longer have to click into a resource in order to perform actions on it.

Calico bug fixes

---

troposphere/static/css/app/dashboard.scss
troposphere/static/css/app/modal.scss
troposphere/static/js/components/dashboard/DashboardPage.react.js
troposphere/static/js/components/modals/project/ProjectInstanceLaunchModal.react.js
troposphere/static/js/components/modals/project/instance_launch/ImageLaunchView.react.js
troposphere/static/js/components/modals/project/instance_launch/InstanceLaunch.react.js
troposphere/static/js/components/modals/volume/VolumeCreateModal.react.js

Make ability to request more resources more visible to users from dashboard and launch modals

Add more resource links

---

troposphere/static/css/app/header.scss
troposphere/static/css/app/layout.scss
troposphere/static/js/components/Header.react.js

Fixed responsive layout of navigation that was hiding content on page.

fixed nav screen sizes, issue Atmo-881

---

troposphere/static/css/app/app.scss
troposphere/static/css/app/applications.scss
troposphere/static/js/components/images/detail/EditImageDetails.react.js
troposphere/static/js/components/images/detail/ViewImageDetails.react.js
troposphere/static/js/components/images/detail/description/EditDescriptionView.react.js
troposphere/static/js/components/images/detail/versions/Version.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js
troposphere/static/js/components/modals/image_version/licenses/CreateLicenseView.react.js
troposphere/static/js/components/modals/image_version/licenses/LicenseMultiSelectAndCreate.react.js
troposphere/static/js/components/modals/image_version/scripts/CreateScriptView.react.js
troposphere/static/js/components/modals/image_version/scripts/ScriptMultiSelectAndCreate.react.js

Fixed the missing styles and layout that was missed on last merge of image_creator

Image creator style fix

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

- Cleanup (Remove unused var)
- Fix back on item 2
- Fix moving to review page

Cleanup forward and backward movement in instance modal

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

This fix does not yet resolve the project page, which is WIP.

Fix back when image page of modal not active

---

gulp/tasks/sass.js
package.json

Added gulp-autoprefixer to the SASS task to fix some browser issues

add Autoprefix to gulp

---

troposphere/static/js/components/dashboard/DashboardPage.react.js
troposphere/static/js/components/dashboard/InstanceHistoryList.react.js

API exposed to new attributes for the 'instance_history' details endpoint: image and provider. This eliminates the need to do nested queries from the client-side.

Updated UI to use new API changes for instance history

---

troposphere/static/css/app/dashboard.scss

This is a quick fix to hide the text that overflows the Activity card. I'm going to refactor all cards to use the same card component so a better solution will be implemented there.

quick fix, working on a general solution

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/components/modals/instance/launch/steps/NameIdentityVersionStep.react.js
troposphere/static/js/components/modals/instance/launch/steps/ReviewLaunchStep.react.js
troposphere/static/js/components/modals/instance/launch/steps/SizeSelectStep.react.js

This addresses JIRA ticket ATMO-800

Add resource modal links

---

package.json
troposphere/static/css/app/common.scss
troposphere/static/css/app/layout.scss
troposphere/static/js/components/projects/detail/resources/ProjectResourcesWrapper.react.js
troposphere/static/js/components/projects/detail/resources/SelectableRow.react.js
troposphere/static/js/components/projects/detail/resources/SelectableTable.react.js
troposphere/static/js/components/projects/detail/resources/instance/InstanceList.react.js
troposphere/static/js/components/projects/detail/resources/instance/InstanceRow.react.js
troposphere/static/js/components/projects/detail/resources/instance/InstanceTable.react.js
troposphere/static/js/components/projects/detail/resources/volume/VolumeList.react.js
troposphere/static/js/components/projects/detail/resources/volume/VolumeRow.react.js
troposphere/static/js/components/projects/detail/resources/volume/VolumeTable.react.js

Makes tables, with provided classes, responsive (rows become cards). Hides thead and applies label to td with sudo element using an attribute supplied to the td markup.

Responsive tables

---

troposphere/static/js/components/Master.react.js
troposphere/static/js/components/modals/unsupported/modernizrTest.js

Makes unsupported modal appear at appropriate time.

fixed boolian check on Master.js, removed console.log's from unsupportedTest.js

---

package.json
webpack.config.js

We can merge this with JJ as well

Added autoprefixer to webpack for css browser support

---

troposphere/static/js/actions/NullProjectActions.js
troposphere/static/js/components/Master.react.js
troposphere/static/js/components/modals/nullProject/NullProjectMigrateResourceModal.react.js
troposphere/static/js/components/modals/unsupported/UnsupportedModal.react.js
troposphere/static/js/components/modals/unsupported/modernizrTest.js
troposphere/static/js/modals/unsupported/showUnsupportedModal.js

Calling NullProjects if Unsupported check passes, otherwise NullProjects is called on UnsupportedModal submit. Also, fixed bug on NullProjects causing projects to be overridden with null.

UnsupportedModal and NullProjects fix

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/components/modals/instance/launch/steps/NameIdentityVersionStep.react.js
troposphere/static/js/components/modals/instance/launch/steps/ReviewLaunchStep.react.js
troposphere/static/js/components/modals/instance/launch/steps/SizeSelectStep.react.js

Redo PR #139 which adds resource request links to instance launch modals. For some reason, this change was not merged into Incana Incana, so this PR addresses that.

Redo modal links

---

troposphere/static/js/stores/VolumeStore.js

I currently have no ATMO ticket number for this issue. It was discovered while triaging [ATMO-747](https://pods.iplantcollaborative.org/jira/browse/ATMO-747).

Fix instance delete with attached volumes

---

troposphere/static/resources/js/cf2/views/feedback_link.js
troposphere/static/resources/js/cf2/views/notification_holder.js

Unfortunately updating the indent before applying my changes really obfuscated what I did.
This is part of [ATMO-991](https://pods.iplantcollaborative.org/jira/browse/ATMO-991)

Fix airport forms

---

troposphere/static/js/components/modals/instance/launch/steps/ReviewLaunchStep.react.js

I missed this last step first PR here:
https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/177/files

update to missed last step

---

package.json
troposphere/settings/default.py
troposphere/static/js/components/images/list/ImageListView.react.js
troposphere/static/js/public_site/AppRoutes.react.js
troposphere/static/js/public_site/bootstrapper.react.js
troposphere/static/js/public_site/main.js
troposphere/templates/index.html
troposphere/views/app.py
webpack.config.js

Troposphere's 'public site' has been neglected over the last few releases and some file changes were necessary to get it up and running again.

Fix the public site for Troposphere

---

troposphere/static/js/actions/HelpActions.js
troposphere/static/js/modals/help/showFeedbackModal.js
troposphere/static/resources/js/cf2/views/feedback_link.js

One notable change is that both clients send the json:
{ "message": "everything is borked", "user-interface": ... }
Before message was an object containing extra stuff.
Should be merged with corresponding atmosphere fix-forms PR.

Update both airport/troposphere to use email/feedback api v2

---

troposphere/static/js/components/admin/IdentityMembershipAdmin.react.js
troposphere/static/js/components/common/InteractiveDateField.react.js
troposphere/static/js/components/images/detail/removed/EditRemovedView.react.js

With #185, we included components for resolving ATMO-987 on `master` (aka `kicking-kestrel`). However, this components are needed in `jamming-junglefowl`. 
(cherry picked from commit 0ebf001e4670e1b0f66ade519207745af0accb20)

Include missing components from Image end-dating.

---

troposphere/static/js/AppRoutes.react.js
troposphere/static/js/components/images/ImagesMaster.react.js

**Fixes the Following:**
The admin page defaults to "Manage Users" but the corresponding Secondary Menu item doesn't appear active. This was fixed in the original PR for ATMO-1062 but was missed in the merg.

Patch for ATMO-1062

---

troposphere/templates/index.html

Changed to honor the SITE_TITLE in index.html template.

---

troposphere/static/js/components/Footer.react.js

**Note:** This should be backported as a "configuration" parameter in the future.

Altered link in the Footer, hardcode, to Jetstream project page.

---

troposphere/static/css/app/admin.scss
troposphere/static/css/app/modal.scss
troposphere/static/js/components/common/AUCalculator.react.js
troposphere/static/js/components/modals/RequestMoreResourcesModal.react.js

Use new AU calculator component, update help text in request box with a more reasonable example.

Add AU calculator, update resource request modal help text

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/collections/SSHKeyCollection.js
troposphere/static/js/components/modals/SSHKeyUpload.react.js
troposphere/static/js/components/modals/skeleton.react.js
troposphere/static/js/components/settings/AdvancedSettingsPage.react.js
troposphere/static/js/components/settings/SettingsPage.react.js
troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js
troposphere/static/js/models/Profile.js
troposphere/static/js/models/SSHKey.js
troposphere/static/js/stores/SSHKeyStore.js

**Major features:**
- Management of public keys through tropo settings
- Toggle use of ssh keys
- Tropo settings now features expandable advance config section
**Default:**
**After "show more":**
**Add a key:**
See JIRA [ticket](https://pods.iplantcollaborative.org/jira/browse/ATMO-649).
Associated atmosphere [PR](https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/69).
Associated ansible [PR](https://github.com/iPlantCollaborativeOpenSource/atmosphere-ansible/pull/4)

[ATMO-649] Atmosphere stores or generates ssh keys for use within a vm

---

troposphere/static/js/components/modals/RequestMoreResourcesModal.react.js

Add some info text in the allocation request modal about the monthly allocation allowance rest.

Add AU reset info

---

troposphere/static/js/actions/HelpActions.js
troposphere/static/resources/js/cf2/views/feedback_link.js

Match the proper endpoint for `api/v2`

Fix feedback forms

---

troposphere/static/resources/js/cf2/router.js
troposphere/templates/cf2.html

the request didn't define that it expected JSON
*Before:*
*After:*
Todo:

Fix footer

---

troposphere/templates/cf2.html

Fix logo and header in cloudfront

---

troposphere/static/js/no_user.js
troposphere/templates/no_user.html

Changed the `no user` pages to point to CyVerse instructions. 

---

troposphere/static/js/actions/instanceVolume/attach.js
troposphere/static/js/stores/BaseStore.js

A collab between @prosif and @cdosborn fixing code we broke.

Fix broken volume attach

---

troposphere/static/js/components/images/detail/versions/VersionList.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js
troposphere/static/js/components/modals/image_version/requirements/EditMinimumRequirementsView.react.js
troposphere/static/js/components/modals/instance/launch/steps/SizeSelectStep.react.js

Allow users to edit their image's minimum requirements through the image edit modal.

Edit min requirements

---

troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js
troposphere/static/js/modals/project/moveResources.js

This fixes the issue filed:
https://pods.iplantcollaborative.org/jira/browse/ATMO-1009

[ATMO-1009] Fix 'Moved resources appear in dialog after being moved'

---

troposphere/static/js/components/common/InteractiveDateField.react.js
troposphere/static/js/components/images/detail/EditImageDetails.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js
troposphere/static/js/models/Image.js

Fixes [ATMO-1166](https://pods.iplantcollaborative.org/jira/browse/ATMO-1166).

Correct handling of null `end_date`

---

troposphere/static/css/app/admin.scss
troposphere/static/js/AppRoutes.react.js
troposphere/static/js/actions/ImageRequestActions.js
troposphere/static/js/components/admin/ImageMaster.react.js
troposphere/static/js/components/admin/ImageRequest.react.js
troposphere/static/js/components/admin/ResourceMaster.react.js
troposphere/static/js/components/admin/ResourceRequest.react.js
troposphere/static/js/stores/BaseStore.js

**Depends on Atmo PR 103**
Update jetstream branch resource requests to look nicer/have individual detail pages and update machine requests to have similar structure/functionality.
Also add nice spinning refresh buttons on both request admin pages

Jetstream machine request fixes

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

Curly brackets and semicolons were missed while reformatting.

Added curly brackets and semicolons to if statements

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

Just including this as a patch for Mystifying Merlin. Fixes the state bug outlined in ATMO-1203

Cherry pick bug fix ATMO-1203

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/components/modals/instance/launch/components/ImageList.react.js
troposphere/static/js/utilities/filterCollection.js

A patch from master to filter End Dated images and versions using new Collection methods.

Atmo 1243 for mm

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/collections/FunctionalCollection.js
troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js
troposphere/static/js/components/modals/instance/launch/steps/NameIdentityVersionStep.react.js
troposphere/static/js/models/InstanceState.js
troposphere/static/js/utilities/filterCollection.js

_(Sorry for the formatting, I have commented the lines that were actually changed in this PR)_
The reason it isn't just the filter callback is because it also returns a new collection rather than an array which is the standard behavior of filter on collections. 
This is a temporary solution,
Connor is working on a solution that will add methods to all of our collections. In this case the filterEndDate function would be reduced to a simple callback and used like ` collectionName.cfilter(callbackName) ` 
This is better because then filter methods can be chained together.

Jetstream filtered end date

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/components/modals/instance/launch/components/ImageList.react.js
troposphere/static/js/utilities/filterCollection.js

Updating the New Instance Launch Modal and the filterEndDate utility to use Connor's sweet `cfilter()` method.

Strip filterEndDate down to cb, and use connor's cfilter

---

troposphere/static/css/app/TabLinks.scss
troposphere/static/css/app/app.scss
troposphere/static/js/components/common/ui/TabLinks.react.js
troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js

This is targeting Mystifying Merlin with The Tabbed Interface for the "Image Select Step" on the "Instance Launch Modal"  that was introduced to Master (N-N) in this PR: #299 
As per request by sir @steve-gregory

Tabbed filters for mm

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

Adds to #319 missed a reference to 1000 that should have been 1024

missed value to change

---

package.json

See @a8144d21def for more details

Update bootstrap-sass, since bug is fixed in latest stable

---

troposphere/templates/no_user.html

See [ATMO-1229](https://pods.iplantcollaborative.org/jira/browse/ATMO-1229).

Re-introduce toast dialog messages in /forbidden view

---

troposphere/static/js/collections/HelpLinkCollection.js
troposphere/static/js/components/help/HelpPage.react.js
troposphere/static/js/components/images/ImageListPage.react.js
troposphere/static/js/components/images/MyImageRequestsPage.react.js
troposphere/static/js/components/images/MyImagesPage.react.js
troposphere/static/js/components/projects/InstanceDetailsPage.react.js
troposphere/static/js/components/projects/ProjectResourcesPage.react.js
troposphere/static/js/components/projects/VolumeDetailsPage.react.js

See [ATMO-1230](https://pods.iplantcollaborative.org/jira/browse/ATMO-1230)

Revive Help Links through new Atmosphere v2 endpoint

---

troposphere/static/js/actions/Utils.js
troposphere/static/js/actions/instance/report.js
troposphere/static/js/actions/volume/report.js
troposphere/static/js/modals/help/requestMoreResources.js
troposphere/static/js/modals/instance/report.js

There's a corresponding atmo pull for this..
[Atmo PR](https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/135)
[ATMO-991](https://pods.iplantcollaborative.org/jira/browse/ATMO-991)

[ATMO-991] fix email

---

troposphere/static/js/components/images/list/common/ImageCard.react.js
troposphere/static/js/components/images/list/common/ImageListCard.react.js
troposphere/static/js/components/images/list/grid/ImageCardGrid.react.js
troposphere/static/js/components/images/list/list/ImageCardList.react.js

Adds an End Dated ribbon to images that have been End Dated for image owners to quickly identify that an image is such.

[ATMO-1146] Identify enddated imgs

---

troposphere/static/js/components/providers/Instances.react.js

Breaks down AU usage per provider,
* By Instance
And per instance,
* By Instance History

Show AU Usage Breakdown

---

troposphere/templates/cf2.html

💀 Re-include the favicon.ico

---

troposphere/static/js/components/projects/resources/instance/details/sections/metrics/CPUGraph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/Graph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/GraphController.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/MemoryGraph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/NetworkGraph.js

The es2015 refactor exposed some 🐛   in the `InstanceGraph` code.

Fix console errors relating to graphs

---

.esformatter
troposphere/static/js/components/images/detail/versions/Version.react.js

This cleans up some sloppy errors. I'm going to submit a PR for a script I use to check my code before I push, that I'd appreciate feedback on.

Fix converter error

---

troposphere/static/js/components/admin/AdminMaster.react.js

Add missing import for navigation

---

troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js

Here's my approach to https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/389. I didn't want to stomp on that pr's commits.

🌷 Clear favorites list on Instance Launch Wizard

---

.eslintrc.strict
package.json
troposphere/static/js/controllers/NotificationController.js

Toastr notification now disappear after 5 seconds (errors and warnings do not).

Fix toastr defaults, notifs fade out

---

troposphere/static/js/components/modals/link/ExternalLinkCreateModal.react.js
troposphere/static/js/components/modals/link/ExternalLinkDeleteModal.react.js
troposphere/static/js/modals/link/createAndAddToProject.js
troposphere/static/js/modals/link/destroy.js

I unwound #392, and added some niceties. This was mostly @steve-gregory's work.
I fixed some prop types issues, and decided to cut the validation. When this gets the okay i will run the formatter and linter.

Atmo 1217 allow links with same name

---

.eslintrc
.eslintrc.strict
.eslintrc.travis
LINT.md

Address errors in `eslint` config, 😠 pretty sure this isn't an error see [eslint docs](http://eslint.org/docs/user-guide/configuring#configuring-rules).

Fix linter config

---

troposphere/static/css/app/common.scss
troposphere/static/js/components/projects/detail/resources/link/ExternalLinkTable.react.js

@julianpistorius pointed out that Url should be URL. It's in the changes despite the image.

Fix external link et tables

---

troposphere/static/css/app/header.scss
troposphere/static/js/components/Header.react.js

This PR changes the Beta Toggle Button Color and switches the CSS from a stylesheet to inline styles

Enhancement: Beta Toggle Color

---

troposphere/themes/README.md

This PR includes a README in the themes dir. explaining how to create a custom theme for troposphere.

Add theme documentation

---

troposphere/static/resources/css/cloudfront.css
troposphere/templates/cf2.html

Adds a 'Hello Bar' style nag message to airport that will encourage users to upgrade, let them know airport will be discontinued sept 20, if they don't want to upgrade a modal is provided containing an  [embedded google form survey](https://docs.google.com/forms/d/e/1FAIpQLScHUJBVuELCznaUNale__3grv5dT2K36RUBGFCWEW2VZn4SXA/viewform) to help us make Troposphere better.

make hello bar and embed form into modal

---

troposphere/static/css/app/app.scss
troposphere/static/css/app/header.scss
troposphere/themes/troposphere_theme/css/login.css
troposphere/themes/troposphere_theme/css/theme.css
troposphere/themes/troposphere_theme/scss/_nav.scss
troposphere/themes/troposphere_theme/scss/theme.scss

Remove refs to 'BETA' and it's Var

---

Makefile
troposphere/views/app.py
troposphere/views/maintenance.py

The app is trying to load the theme from `/themes/$THEME_NAME`, but it should be
loading from `/assets/theme`.
This will need a corresponding fix in clank, since `make cf2` is no longer a command.

Fix incorrect theme path

---

troposphere/static/js/actions/instance/requestImage.js
troposphere/static/js/components/modals/instance/InstanceImageWizardModal.react.js
troposphere/static/js/components/modals/instance/image/components/Tags.react.js
troposphere/static/js/components/modals/instance/image/steps/ImageInfoStep.react.js
troposphere/static/js/stores/TagStore.js

As stated in the title, this will allow the UI to filter out "black listed" tags for non staff users.
More Details can be found in [The Atmosphere PR](https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/189)

Use new Tag field 'allow_access' to determine if user can add a Tag to resource.

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

If someone can try this on atmo-dev that would be awesome as I am working in the dark with sunglasses and one finger. 
**With projects** 
- Launch from project resource page _(should see select Image View)_
- Navigate to an image detail, refresh and try to launch _(should see basic launch view)_
**Without Projects**
- Navigate to an image detail, refresh and try to launch _(should see create project view)_
- Create a project and submit _(should see basic launch view)_
- Test modal for basic working order

Add test for project list

---

troposphere/static/css/app/common.scss
troposphere/static/css/app/layout.scss
troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js

remove side detail panel and restyle

---

troposphere/static/js/components/modals/instance/image/components/Tags.react.js

This was work that I intended to tack onto https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/435.
I think this is cleaner.

Cleanup Tags from branch ATMO-1305

---

troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js
troposphere/static/js/models/Profile.js

https://pods.iplantcollaborative.org/jira/browse/ATMO-1475 (Atmosphere PR [195](https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/195))

ATMO-1475 SSH Key UX needs improvement

---

troposphere/static/js/components/common/tags/Tag.react.js
troposphere/static/js/components/images/ImageListPage.react.js
troposphere/static/js/components/images/list/ImageListView.react.js

Clicking a tag in an image card was broken (along with other behavior mentioned in the ticket below). I introduced this regression.. 😢 . To better times 🍻 
https://pods.iplantcollaborative.org/jira/browse/ATMO-1491

ATMO-1491 fix tag links

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

This adds a test for our project list that [this PR](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/443) had missed.

Fix missing test for project list

---

troposphere/templates/allocations.html
troposphere/views/allocations.py

See [JETSTREAM-45](https://iujetstream.atlassian.net/projects/JETSTREAM/issues/JETSTREAM-45).

Reword the "no allocation" text on landing page

---

troposphere/static/js/components/common/ui/tooltips/ResourceUseTooltip.react.js
troposphere/static/js/components/dashboard/DashboardPage.react.js
troposphere/static/js/components/dashboard/plots/tooltips/ResourceUseTooltip.react.js

By community member resource from Jetstream (via [JETSTREAM-67](https://iujetstream.atlassian.net/browse/JETSTREAM-67)).

Change the tense in the resource usage tooltip

---

troposphere/static/js/components/admin/ImageRequest.react.js

Bugfix: 'bool-strings' always evaluated to 'Truthy'.

---

troposphere/static/js/components/dashboard/InstanceHistoryList.jsx

Fixes #503.
Thank you Joseph Garcia (@prosif).

Problem: no space between text & Image link for Instance History

---

troposphere/static/js/components/settings/AdvancedSettingsPage.jsx

Remove 'Export Credentials' from Advanced Settings

---

PULL_REQUEST_TEMPLATE.md

A PR template was requested as part of the improvements to the contribution and development process of Troposphere.
Included is a sample PR template for consideration.

Create PULL_REQUEST_TEMPLATE.md for Troposphere

---

extras/logrotate.troposphere

Use date extension file naming for logrotate for easy archiving.

---

troposphere/templates/index.html

fix a typo for index.html

---

troposphere/static/js/components/common/AllocationSourceGraph.jsx
troposphere/static/js/components/dashboard/plots/AllocationSourcePlot.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourceGraphs.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourcesForm.jsx
troposphere/static/js/messages/allocationMessages.js

This extracts the "copy" text, phrases, and unit names into a module to help move toward an Internationalized/Localized version of the user interface. The module is selected based on the deployment's allocation strategy/approach.
See [JETSTREAM-18](https://iujetstream.atlassian.net/browse/JETSTREAM-18)

Problem: allocation text, phrases, & units specific to CyVerse

---

troposphere/static/js/components/common/AllocationSourceGraph.jsx
troposphere/static/js/components/dashboard/plots/AllocationSourcePlot.jsx
troposphere/static/js/components/modals/RequestMoreQuotaOrAllocationModal.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourceGraphs.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourcesForm.jsx
troposphere/static/js/messages/allocationMessages.js
troposphere/static/js/modals/help/requestMoreResources.js

This work introduces an resource request to allow for either "quota" or "allocation" requests. In the case of allocation, a reference to the proper user portal is provided since the portal is the only way to make requests. 
See [JETSTREAM-20](https://iujetstream.atlassian.net/browse/JETSTREAM-20).

Problem: Resource Requests are specific to CyVerse

---

troposphere/static/js/components/Header.jsx
troposphere/static/js/components/images/detail/header/HeaderView.jsx
troposphere/static/js/components/modals/ExpiredPassword.jsx
troposphere/static/js/components/projects/detail/resources/SubMenu.jsx
troposphere/static/js/context.js
troposphere/static/js/modals/expiredPassword/show.js
troposphere/static/js/models/Profile.js

Reinclude lenards/atmo-1481 that was lost in merge
In d05bc92831, feature lenards/atmo-1481 was merged. In a later merge 807c7d6247be, the feature was excluded. This is a "remerge" to include lenards/atmo-1481.

Reinclude lenards atmo 1481

---

package.json
requirements.in
requirements.txt
troposphere/settings/local.py.j2
troposphere/static/js/components/Master.jsx
troposphere/static/js/components/SplashScreen.jsx
troposphere/static/js/main.js
troposphere/templates/index.html
troposphere/views/app.py

Problem: The previous integration using raven.js (only) provided insufficient data about production errors.
Solution: 
- Use raven via Django to provide the js library.
- Include additional User context and Tag context (server_name)
- Verified that emulation works as expected, that productions builds work as expected.

Improved Sentry Integration

---

test/bdd/README.md

For use in BDD/selenium testing.

Include instructions for headless chrome

---

troposphere/static/js/components/projects/detail/resources/tableData/instance/Activity.jsx

> Note: This is change is meant to assist community members in getting their instances back in a usable state. I have approval from the product owner and a member of the leadership team. 
It is not entirely clear what action might help get an instance out of a "deploy_error". This provides a small "info-sign" icon with a `react-tooltip` on mouse over to suggest an action to resolve the error.

Problem: not clear how to resolve an instance in "deploy_error"

---

troposphere/settings/default.py
troposphere/static/js/modals/help/requestMoreResources.js

I was wondering why it says "Undulating Umbrellabird"

fix version for Y release

---

troposphere/static/js/components/projects/detail/resources/tableData/instance/Activity.jsx

Its hard to see whats going on here. Because github is inlining all the commits from the merges.
Here are the two commits I tacked onto master:
```bash
git log --oneline --first-parent origin/master..master
7db076157 Trickle down changes from 'origin/xylotomous-xenops'
7ef777349 Bring in olds tips but ignore their changes
```
7db07615705d0188107a8cd79f98623e0c87338b merges old releases into master, but ignores their changes. 
7ef777349309dec58bb4dad8ea9d1f125c4cd055 brings in the following history from x-x
```
git log --oneline origin/master..origin/xylotomous-xenops 
6ecfd8b88 Merge pull request #607 from lenards/x-x-deploy-error-assist-tooltip
421c6d91b Apply feedback on tooltip wording
6488a240b Suggest action resolution for deploy_error
```

Update master to include missing work from releases

---

FEATURE_INFO_TEMPLATE.txt

This document started out in a GitHub repo [\[0\]](https://github.com/Tharon-C/product-req-doc) as a Markdown document [\[1\]](https://github.com/Tharon-C/product-req-doc/blob/master/prd_temp.md). Here, we've changed to the JIRA/Confluence specific markup to make it easier for inclusion within JIRA tickets.
Once added to the repository, we can track versions are the usage of the template affords the opportunity to improvement it for the habits of the team, overall.
@Tharon-C should be attributed as the _author_ of this template.
\[0\] https://github.com/Tharon-C/product-req-doc
\[1\] https://github.com/Tharon-C/product-req-doc/blob/master/prd_temp.md

Problem: Add feature information template

---

test/bdd/README.md

fix a typo in ReadMe

---

.travis.yml
travis/check_properly_generated_requirements.sh

When I added requirements checking to atmosphere's .travis.yml I fixed an issue and added some niceties. This PR just includes those. This version of the script has nice output (colorized and is more vocal). It also upgrades setuptools along with pip which are both really old by default. (we wouldn't need to install setuptools, if we used pip-compile from within a virtual env)

Fix travis requirements script

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx

Add missing paramater provider

---

troposphere/static/js/components/projects/resources/instance/details/sections/AllocationSourceSection.jsx

Fix broken "Request more resources" when allocation usage exceeded 100% on instance details page.

Fix instance detail missing Request More Resources handler

---

.travis.yml

Small change so that the travis check for migrations doesn't create missing migrations.

Do not generate missing migrations  💅 

---

REQUIREMENTS.md

I don't think it was clear that most likely you just want to do `git compile -P <package`. Tried to make that front and center.

Make it more clear how to upgrade packages

---

PULL_REQUEST_TEMPLATE.md

This is a companion PR to https://github.com/cyverse/atmosphere/pull/422. See that description.

Add requirements for new variables

---

troposphere/static/js/components/common/InstanceDetail.jsx

Fix the broken build. This will have to be brought into master. Because v27 was merged into master with the broken commit.

Fix broken build V27

---

travis/check_properly_generated_requirements.sh

Just bringing in changes to improve the check requirements script that were added in atmosphere.

Make travis requirements check more robust

---

dev_requirements.txt
requirements.in
requirements.txt
troposphere/views/auth.py

Two things going on here. 
@aa9d556b: Bring in the original changes to django-cyverse-auth (and use updated api)
@b1d5261: Bring in the hotfix to those changes

v27 fix missing django cyverse auth hotfix

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/components/BasicInfoForm.jsx

Add missing props and function to InstanceLaunchWizardModal

Problem: Identity list doesn't load when project sharing is enabled

---

troposphere/settings/default.py

Please let me know if I should change it to another name. Thanks!

Problem: Change to v27 in default.py

---

troposphere/settings/local.py.j2
troposphere/wsgi.py

Solution: Provide optional support for new relic via template

Problem: New relic must be added after template configuration

---

troposphere/static/js/actions/VolumeActions.js
troposphere/static/js/actions/volume/create.js
troposphere/static/js/components/common/ui/WaitingIndicator.jsx
troposphere/static/js/components/modals/instance/launch/components/IdentitySelect.jsx
troposphere/static/js/components/modals/instance/launch/components/InstanceLaunchFooter.jsx
troposphere/static/js/components/modals/volume/VolumeCreateModal.jsx
troposphere/static/js/modals/instance/launch.js
troposphere/static/js/modals/volume/createAndAddToProject.js
troposphere/static/js/models/Volume.js
troposphere/static/js/stores/BaseStore.js

- Project + Volume associated on creation time
**- [WIP] Volume updating does not yet work!**

Problem: Project not included in volume creation

---

troposphere/static/js/components/modals/nullProject/NullProjectMigrateResourceModal.jsx
troposphere/static/js/stores/IdentityStore.js

Fix misuse of id, uuid where id was expected

---

troposphere/static/js/components/common/boot_script/EditScript.jsx

Remove 'this.hide()' from offending component.

Problem: Error when creating boot script from settings

---

troposphere/settings/default.py

Shamefully sending one line code change contribution.

Change the default UI_VERSION

---

troposphere/static/js/actions/script/create.js
troposphere/static/js/actions/script/create_AddToImageVersion.js
troposphere/static/js/actions/script/update.js
troposphere/static/js/components/common/boot_script/EditScript.jsx
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.jsx

Solution: Include  missing parameters, `strategy` and `wait_for_deploy` in create and update for ScriptActions

Problem: some BootScript parameters not respected

---

troposphere/static/js/components/modals/nullProject/NullProjectMigrateResourceModal.jsx

This pull request makes it to a "new project" action is handled by the "Migrate Resources" modal. 
The new project will appear, as expected, in the Project drop down.

Problem: New projects not shown in "Migrate Resources" modal

---

troposphere/views/web_desktop.py

- Handle 404 by returning that 404 error as response for /web_desktop. 
- Log any other, unexpected failure and return 502 instead of crashing.

Problem: failures in /web_desktop cause 500 errors

---

troposphere/static/js/components/projects/resources/instance/details/actions/InstanceActionsAndLinks.jsx

Begin deprecate existing web desktop and shell

---

package.json
troposphere/settings/default.py
troposphere/static/js/components/admin/ImageMaster.jsx
troposphere/static/js/components/admin/ImageRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequestView.jsx
troposphere/static/js/components/common/boot_script/EditScript.jsx
troposphere/static/js/components/settings/advanced/SSHConfiguration.jsx
troposphere/static/js/components/settings/advanced/ScriptListView.jsx

Just bringing master up to date so I can submit feature work on master:

Bring v30 work into master

---

troposphere/static/js/components/admin/ImageMaster.jsx
troposphere/static/js/components/admin/ImageRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequestView.jsx
troposphere/static/js/components/settings/advanced/SSHConfiguration.jsx

Bring last remaining bit of v30 into v31

Merge v30 into v31

---

CHANGELOG.md
PULL_REQUEST_TEMPLATE.md
package.json
troposphere/settings/default.py

Kick off new release, and while i'm at it proposing changes to make changelog easier to maintain.
I looked around and found a documented changelog format [here](http://keepachangelog.com/en/1.0.0/). Its basically what we're currently doing now, but it has a way to collect change that are in an upcoming release. I would like it to be a requirement that each PR updates the changelog following that format, so that come time for release the work has already been done. 
- https://github.com/cdosborn/troposphere/blob/838dce90eac19f6f4e09196e93ed27cdfe8532ad/CHANGELOG.md

Start of v33

---

.travis.yml
CHANGELOG.md
troposphere/management/commands/maintenance.py
troposphere/management/commands/test_maintenance.py

See https://github.com/cyverse/atmosphere/pull/596
- https://github.com/cyverse/atmosphere-guides/pull/39

Change maintenance command to be non-interactive

---

CHANGELOG.md
troposphere/static/js/actions/ProjectActions.js
troposphere/static/js/components/common/ProjectCreateView.jsx
troposphere/static/js/components/projects/detail/details/EditDetails.jsx

Remove requirement of projects to have a description
Resolves https://github.com/cyverse/troposphere/issues/634

Do not require a project description on project create

---

CHANGELOG.md
troposphere/settings/local.py.j2
variables.ini.dist

See https://github.com/cyverse/atmosphere/pull/665

Remove unused variable SERVER_EMAIL

---

CHANGELOG.md
troposphere/static/js/components/projects/detail/resources/TableActions.jsx
troposphere/static/js/components/projects/detail/resources/instance/InstanceTable.jsx
troposphere/static/js/components/projects/detail/resources/volume/VolumeTable.jsx
troposphere/static/js/utilities/comparators.js

JETSTREAM-104: Enhancement, add sorting to instance and volume tables in project resources.

JETSTREAM-104: sort options on project resources

---

troposphere/static/js/components/modals/instance/InstanceStopModal.jsx

I accidentally messed up the formatting while merging PRs and fixing conflicts.
Sorry for all the failed Travis runs :cry: :sob:

Fix formatting

---

CHANGELOG.md

Update changelog to release Troposphere v36-0

Release Troposphere v36-0

---

dev_requirements.txt
requirements.in
requirements.txt

Update to Django 1.11.23

---

CHANGELOG.md

This PR updated the changelog to release v36-4
v36-3 is skipped to stay on the same version as Atmosphere

Update changelog to release v36-4

---

.travis.yml
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/steps/LicenseStep.jsx

Fix submit on license step in launch wizard and add wheel package.

---

CHANGELOG.md

Update Troposphere changelog to v36-5

---

troposphere/static/js/components/help/HelpPage.jsx

per Intercom ticket: https://app.intercom.com/a/apps/tpwq3d9w/inbox/inbox/910154/conversations/27146959852

Removed 'User Forums' section

---

CHANGELOG.md
troposphere/static/js/components/help/HelpPage.jsx

Release v36-6
