api/serializers.py
api/urls.py
api/views.py
troposphere/auth_backends.py
troposphere/settings/default.py

1. Expose API endpoint for users.  Currently limited to return only the current user's information.
2. Expose API endpoint for user preferences.  Currently limited to return only the current user's preferences.
3. Added OAuthToken backend to allow for a CAS token to be sent in an API request to interact with the API.
4. Updated token authentication so that the user is automatically created if a) the token is valid and b) user doesn't already exist.

Expose user preferences in api

---

requirements.txt
troposphere/auth_backends.py
troposphere/static/js/components/applications/detail/EditApplicationDetails.react.js
troposphere/static/js/components/applications/detail/ViewApplicationDetails.react.js

This re-enables the ability for image owners to edit the name, description and tags of images they own.
1. The core issue why users couldn't edit images anymore was because **image.created_by** is now a resource, and not just a username anymore.  So I needed to add **image.created_by.username** to fix the logic check for whether to show the edit link.  There was also a secondary issue related to the component trying to use the **ImageTagStore** instead of the **TagStore** to get all the tags for an image.  While **ImageTagStore** is the correct store, it doesn't actually exist in the UI code at the moment.  But it should be added later and current code should be updated to use it.
2. Fixed the CAS OAuth login flow (there was a bug about user not being defined)
3. Dropped Django version …

Fix owner image edit

---

troposphere/static/js/components/Header.react.js

This fixes a bug where the admin view to modify resource requests is shown to everyone and not just staff.

only show admin view to staff

---

troposphere/static/js/components/modals/ModalHelpers.js
troposphere/static/js/components/modals/VersionInformationModal.react.js
troposphere/static/js/modals/help/requestMoreResources.js
troposphere/static/js/modals/help/showFeedbackModal.js
troposphere/static/js/modals/instance/createAndAddToProject.js
troposphere/static/js/modals/instance/destroy.js
troposphere/static/js/modals/instance/launch.js
troposphere/static/js/modals/instance/reboot.js
troposphere/static/js/modals/instance/report.js
troposphere/static/js/modals/instance/requestImage.js
troposphere/static/js/modals/instance/resume.js
troposphere/static/js/modals/instance/start.js
troposphere/static/js/modals/instance/stop.js
troposphere/static/js/modals/instance/suspend.js
troposphere/static/js/modals/instanceVolume/attach.js
troposphere/static/js/modals/instanceVolume/detach.js
troposphere/static/js/modals/project/create.js
troposphere/static/js/modals/project/destroy.js
troposphere/static/js/modals/project/explainProjectDeleteConditions.js
troposphere/static/js/modals/project/moveResources.js
troposphere/static/js/modals/project/removeResources.js
troposphere/static/js/modals/tag/create.js
troposphere/static/js/modals/tag/create_AddToInstance.js
troposphere/static/js/modals/version/showVersion.js
troposphere/static/js/modals/volume/createAndAddToProject.js
troposphere/static/js/modals/volume/destroy.js
troposphere/static/js/modals/volume/report.js

**Problem**: Every time a modal is rendered React issues the following warning:
```
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
```
**Solution**: Change the approach we use to generate modals.  The three options are described in the following JIRA:
https://pods.iplantcollaborative.org/jira/browse/ATMO-862
After talking with @prosif @erbriones and @steve-gregory solution 3 was selected as the best of the bunch.

Remove modal warnings

---

troposphere/static/js/components/modals/volume/VolumeCreateModal.react.js
troposphere/static/js/components/projects/detail/resources/ButtonBar.react.js
troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js
troposphere/static/js/components/projects/detail/resources/ResourceActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/VolumeActionButtons.react.js

Fixes bug where resource preview pane shows infinite loading after a volume is deleted. This was because the resource was never unselected after deletion, leading to a constant loading of a resource that no longer exists. This is a redone version of PR 97 "fix-volume-loading"

Fix resource loading

---

.gitignore
extras/nginx/Makefile
extras/nginx/locations/tropo.conf.dist
extras/nginx/site.conf.dist

Add nginx configuration to support *standalone* version of troposphere as well as being installed side-by-side with atmosphere.
The site configuration generated is identical between atmosphere and troposphere.
For details on how this works see [#ATMO-PR 41](https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/41)

New nginx structure

---

troposphere/settings/local.py.dist
troposphere/static/css/app/instance.scss
troposphere/static/css/app/instance_metrics.scss
troposphere/static/js/components/projects/resources/instance/details/InstanceDetailsView.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/InstanceMetricsSection.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/CPUGraph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/Graph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/GraphController.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/InstanceMetrics.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/MemoryGraph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/NetworkGraph.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/RefreshComponent.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/Store.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/TimeframeBreadcrumb.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/Utils.js
troposphere/templates/index.html
troposphere/views/app.py
troposphere/views/auth.py

This is the initial release of instance metrics using hyper-stats. It display three graphs (cpu,mem, network) on the instance details pages. It requires the following setting in local.py:
```
SHOW_INSTANCE_METRICS = True
```
It will default to false, otherwise.
If requests to atmo's metrics api fail while the above setting is true, then the instance details page will report that instance metrics are unavailable.

Add instance metrics

---

package.json

imports necessary for instance metrics that were forgotten (:.|)
bootstrap-sass is pointing to github while we are awaiting a fix to a
sass bug (https://github.com/twbs/bootstrap-sass/issues/919)

Include d3, bootstrap-sass master

---

troposphere/static/js/components/modals/ModalHelpers.js
troposphere/static/js/components/modals/volume/VolumeAttachModal.react.js
troposphere/static/js/modals/instanceVolume/attach.js

- Filter instances so that, user cannot attach volumes to instances where the provider doesn't match
- Add bold font, to explain why volumes and instances must have **same provider** and **same project**
- Refactor render modal

Filter instances from different providers when attaching volume

---

troposphere/static/js/components/projects/resources/volume/details/actions/VolumeActionsAndLinks.react.js

This restores the correct behavior of displaying a warning modal on delete in the volume details page.

Delete volume action displays warning modal

---

troposphere/views/emulation.py

When a valid user does not exist on atmosphere an error message is returned. Check the response code for a 404 status.

check if token emulation returns an error

---

troposphere/static/js/components/Master.react.js
troposphere/static/js/components/modals/unsupported/modernizrTest.js

Fix test on master.react.js to boolean so unsupported modal displays appropriately. And removed console.logs from unsupportedTest.js

fixed truthy check on Master.js

---

troposphere/static/js/components/modals/instance/launch/components/Image.react.js

The modal for launching a new instance from a project does not include date/time of an image. This provides a resolution for that ([ATMO-984](https://pods.iplantcollaborative.org/jira/browse/ATMO-984)).
----

Included date/time w/ each image in list when launching from project 

---

troposphere/static/js/actions/HelpActions.js

A resolution for user interface portion of [ATMO-990](https://pods.iplantcollaborative.org/jira/browse/ATMO-990). 
It adds a `user-interface` key to the data payload submitted by the ``HelpAction.js``. 
----

Added indicate of `user-interface` submitting feedback.

---

troposphere/static/js/components/common/project/Project.react.js
troposphere/static/js/components/dashboard/ImageCreatedMessage.react.js
troposphere/static/js/components/dashboard/InstanceHistoryList.react.js
troposphere/static/js/components/images/detail/created/CreatedView.react.js
troposphere/static/js/components/images/detail/removed/RemovedView.react.js
troposphere/static/js/components/images/detail/versions/Version.react.js
troposphere/static/js/components/images/list/common/ImageCard.react.js
troposphere/static/js/components/images/list/common/ImageListCard.react.js
troposphere/static/js/components/modals/VersionInformationModal.react.js
troposphere/static/js/components/modals/image_version/availability/ProviderMachineEditItem.react.js
troposphere/static/js/components/projects/detail/details/EditDetails.react.js
troposphere/static/js/components/projects/detail/details/ViewDetails.react.js
troposphere/static/js/components/projects/list/Project.react.js

This PR simply added the `` ... hh:mm a`` to ``format()`` get the hours, minutes, & am/pm for occurrences where time is currently used. (Resolution for [ATMO-985](https://pods.iplantcollaborative.org/jira/browse/ATMO-985))
Each occurrence does *not* appear to impact the layout of the UI element (see below). 
Examples from local testing are shown below:
----

Added the time (hours:minutes) to dates occurrences.

---

troposphere/static/css/app/modal.scss
troposphere/static/css/app/request_image_form.scss
troposphere/static/js/actions/instance/requestImage.js
troposphere/static/js/components/modals/instance/InstanceImageWizardModal.react.js
troposphere/static/js/components/modals/instance/image/steps/MinimumRequirementsStep.react.js
troposphere/static/js/components/modals/instance/image/steps/ProviderStep.react.js
troposphere/static/js/modals/instance/requestImage.js
troposphere/static/js/stores/BaseStore.js

This PR adds a new step in the image launch modal for users to specify minimum requirements for their images. It also addresses a bug where the step displayed by the modal was incorrectly showing the next step's name when the mouse was hovered on to the breadcrumb and then hovered off.

Add minimum requirements step

---

troposphere/static/css/app/layout.scss
troposphere/static/js/components/projects/common/ResourceDetail.react.js

remove tight aligned labels, two columns, added class selectors to markup.

Fix alignment and keeping break in overflow within own col.

---

troposphere/static/js/actions/HelpActions.js
troposphere/static/js/actions/instance/report.js
troposphere/static/js/actions/volume/report.js
troposphere/static/resources/js/cf2/views/instance_screen/report_instance_form.js
troposphere/static/resources/js/cf2/views/volume_screen/report_volume_modal.js

This provides a simple *data-key* indicating if the originating user-interface was `airport` (aka cloudfront2) or `troposphere`. 
Any reported issue regarding *instances* or *volumes* will include `{"user-interface": '(airport | troposphere'}`. 
This work related to the sub-task [ATMO-1004](https://pods.iplantcollaborative.org/jira/browse/ATMO-1004) for [ATMO-990](https://pods.iplantcollaborative.org/jira/browse/ATMO-990).
- - - -
Also, I included some consistency with the keys for data objects that are defined via object laterals to use double quotes since that adheres with the JSON specification ([see *string* type in grammar](http://www.json.org/)). :neckbeard: 
To my knowledge, their is no performance benefit with using single versus double quotes (if there is some compelling reason …

Provide the originating user-interface for user feedback & issue reporting

---

troposphere/static/js/components/dashboard/plots/ProviderSummaryLinePlot.react.js

Bug: On dashboard, bar-graph hover information doesn't show when bar value is over 100.
Fix: Set value of bar to never exceed 100.

Bug fix ATMO-680: missing hover information on bar-graph

---

troposphere/static/js/components/Header.react.js

Added attributes, data-toggle and data-target, to menu items on small screen sizes that trigger bootstrap's mobile menu functionality. 
Because Bootstrap is using jQuery to manipulate the DOM we need to use data-target to tell Bootstrap where to apply the animation. For this reason, we also need the screen size because trying to animate the menu collapse while it is hidden on larger screen sizes causes buggy looking behavior as it tries to show and hide it.

Fixes ATMO-962 (Clicking on Menu Item not collapsing menu for small screens)

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/components/modals/instance/launch/steps/NameIdentityVersionStep.react.js
troposphere/static/js/components/modals/instance/launch/steps/SizeSelectStep.react.js

The issue was with the `form-horizontal` class applying negative margins to nested `form-group` classes. This is to compensate for the padding added columns, the same issue will occur with the misuse of the `row` class. 
It was fixed by pulling the headings out of the `form-group` classes. Also, the breadcrumb was not nested within the modal body so it just wasn't contained by the body padding.

ATMO-1010 launch modal padding

---

troposphere/static/js/components/images/detail/versions/Version.react.js

There is now a change log displayed on the version card when viewing an image's details just below the author and date created. See below:
**We still need to make some style improvements**
The left side padding of the change log is inappropriate. See below:
The problem here is with the css on the 'app-card' class itself so a small refactor should be done as a separate issue as it effects several components.

Added change log to version card on image detail page

---

troposphere/static/js/components/modals/project/CantMoveAttachedModal.react.js
troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js
troposphere/static/js/modals/ProjectModals.js
troposphere/static/js/modals/project/cantMoveAttached.js
troposphere/static/js/stores/VolumeStore.js

When user tries to move a batch of selected resources, if any resources are attached, a modal alerting the user to first detach the resources stops the user from putting the resource into an inconsistent state. 
**This is a minimum viable solution**
We should display which resources are attached and allow the user to detach from modal. Also, a redesign would help prevent this form happening. I would also suggest letting the user move both resources leaving them attached.

Stop user from moving attached resources ATMO-747

---

package.json
troposphere/static/js/actions/ImageActions.js
troposphere/static/js/components/images/detail/EditImageDetails.react.js
troposphere/static/js/components/images/detail/ViewImageDetails.react.js
troposphere/static/js/components/images/detail/removed/RemovedView.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js
troposphere/static/js/stores/ImageStore.js

*(Summary pulled from #160)*
---- 
Example of the "Input box" users see when they edit their image.
Example of the interface when an object has been end-dated (As seen by image creator or Staff users... "Normal" users will not see the image at all!)

[ATMO-987] Include ability to end date entire image

---

scripts/generate_configs.py

If the config fails, say that the config was not generated.

Be explicit when config is NOT generated

---

api/serializers.py

This provides a true relationship between a troposhere User and their preferences, it address the ticket [ATMO-1052](https://pods.iplantcollaborative.org/jira/browse/ATMO-1052). 
A response to a `GET tropo-api/users/<user-id>` now includes a hyperlink to the `UserPreferences` resource associated with the User. 
```bash
$  curl --insecure -H 'Authorization: Token <TGToken>' \ 
https://ui.atmo.dev/tropo-api/users/1 | python -mjson.tool
{
"date_joined": "2015-09-10T17:29:19.661509Z",
"email": "lenards@iplantcollaborative.org",
"first_name": "Andrew Lenards",
"id": 1,
"is_staff": false,
"is_superuser": false,
"last_name": "Mock Lenards, just try",
"url": "https://ui.atmo.dev/tropo-api/users/1",
"user_pref": [
{
"id": 1,
"url": "https://ui.atmo.dev/tropo-api/user_preferences/1"
}
], …
```

Defined foreign key relation in User to include preferences.  

---

api/migrations/0002_alter_ui_pref_default.py
api/models.py

We want to begin phasing out the previous user interface, *Airport*, in favor of the current version. This will default new users to the current (aka _beta_) user interface. 
This work is a sub-task ([ATMO-1057](https://pods.iplantcollaborative.org/jira/browse/ATMO-1057)) of [ATMO-1016](https://pods.iplantcollaborative.org/jira/browse/ATMO-1016).

Changed the default UI preference for new users.

---

troposphere/static/js/components/dashboard/plots/ProviderSummaryLinePlot.react.js

The `quota` object is exposing the memory as `quota.memory` now;
not `quota.mem`.
This is a fix for [ATMO-1042](https://pods.iplantcollaborative.org/jira/browse/ATMO-1042).

Corrected property used from `quota` to calculate memory usage.

---

troposphere/static/css/app/layout.scss
troposphere/static/js/components/projects/common/SecondaryProjectNavigation.react.js

**Purpose**
* Reduce clutter around options and actions
* Places navigation concerns together above location concerns 
* Is consistent with Images section
**Changes:**
* Moved Project Title block out of secondary nav block and gave it it's own container class
* Removed negative margins from the resource list
* Reduced the bottom margin on Secondary Navigation to 20px

Moved Secondary Navigation above Title 

---

troposphere/static/css/app/admin.scss
troposphere/static/js/actions/AllocationActions.js
troposphere/static/js/bootstrapper.js
troposphere/static/js/components/admin/ResourceAdmin.react.js
troposphere/static/js/constants/AllocationConstants.js
troposphere/static/js/stores/AllocationStore.js

* Allow admins to search for allocations by AU, not have to select from list of threshold/delta values. 
* Abstract delta -1 vs. any other delta value for expiration of allocation to radio buttons.
* Allow creation of new allocation objects from UI, no need to use Django admin for creation
* Don't allow for approval if admin message is empty (updated after screenshot below) or if allocation searched for does not exist

Improve admin page

---

troposphere/static/js/collections/SizeCollection.js

Currently, the instance sizes are shown in an unexpected order. [ATMO-1060](https://pods.iplantcollaborative.org/jira/browse/ATMO-1060). This change altered the instance size comparator to marshal `alias` attribute as an `int` for proper comparison (and not lexical/alpha comparison).
Fix will be available in beta environment. 
A screenshot from the local development environment shows the new ordering:

Corrected instance size order comparison.

---

troposphere/static/js/components/projects/detail/resources/Button.react.js
troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js

This fixes a bug where the tooltip on a button that fires a modal gets stuck open in front of said modal. 
This might be a bug in the browser or a bug with the way the modal and tooltip play with React. 
The easiest solution was to manually hide the tooltip when clicked. 
The onClick event was refactored so that the hiding could happen on the Button component level for reusability without affecting the parents that use it. 
**With Bug**
**Without Bug**

Added tooltip hide option to button onClick event

---

troposphere/static/js/components/projects/resources/instance/details/sections/metrics/InstanceMetrics.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/Utils.js

If the api returned with [], the onError wouldn't fire, because [] is not
falsy in js. Also removed unused import.

Add better error handling for instance metrics

---

troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.react.js

When an instance is selected on the Project Resources page a reboot button will be available on the top right with the other actions. 
This was taken from the Instance Detail page and calls on the same Model (InstanceModels).
**Note: All of these buttons are calling directly to the backbone models**
This will need to be refactored to use actions as we move to redux.

Add Instance Reboot Button to Project Resources Page

---

troposphere/static/css/app/admin.scss
troposphere/static/js/components/admin/ResourceMaster.react.js
troposphere/static/js/components/admin/ResourceRequest.react.js

Clean up the awkward blockiness of a separate admin component taking up half the screen when dealing with resource requests.
Now, requests show as list elements as opposed to table rows, and the admin details and actions vertically expand out when the request is clicked.

Resource Request Admin Cleanup

---

troposphere/static/js/components/images/MyImageRequestsPage.react.js

The machine state column currently shows too much information for the average user. Addresses ATMO-1083.
Non staff user:
Staff user:

Only show image request machine state if user is staff

---

troposphere/static/js/components/modals/instance/image/steps/ImageInfoStep.react.js
troposphere/static/js/components/modals/instance/image/steps/VersionInfoStep.react.js

Addresses the cause of separate issue reported in [ATMO-1083](https://pods.iplantcollaborative.org/jira/browse/ATMO-1083).
Trim text fields using jQuery 's trim() function when checking the current step's isSubmittable() and send the trimmed values to the component's onNext().

Trim values of fields in image request modal before moving to next step

---

troposphere/static/js/actions/instance/destroy.js
troposphere/static/js/stores/BaseStore.js
troposphere/static/js/stores/InstanceStore.js

This fixes an error that is thrown when an instance.update is called on a nonexistent instance. This happens because instances that are polled, are not removed from polling when they are deleted. See this [chunk](https://github.com/cdosborn/troposphere/blob/02fdeb9dc826537524f95960dd7aca15cb728045/troposphere/static/js/stores/BaseStore.js#L91-L95).
To trigger the bug, you have to delete an instance while it's state is still being polled. Normally this doesn't happen, because the polling process doesn't take much time.
There are several stylistic changes. I renamed modelsBuilding to modelsPolling, since that is what it actually represents. We will need to poll for things other than a building instance. Other changes are just whitespace.

Prevent polling of deleted instances

---

troposphere/static/js/components/images/MyImageRequestsPage.react.js

The end date field currently shows the "Invalid Date" text returned by moment.js when trying to parse the "null" returned by the API. In the case of a null end date, display "N/A" which feels a lot better than "Invalid Date."

Show more helpful end date when an image request hasn't been completed

---

troposphere/static/js/components/modals/instance/image/components/Tags.react.js

Re-add tag creation functionality within the image request modal. 
Addresses ATMO-1108

Fix tag creation functionality within image modal

---

troposphere/static/js/components/providers/Stats.react.js

Previously, "time remaining" calculations were done when the number of instances running were 0. This creates a division by zero issue, which ends up be type coerced into `Infinity`. This was displayed to the user as "Infinity hours" remaining.
This address the display of the misleading statistic mentioned in [ATMO-1093](https://pods.iplantcollaborative.org/jira/browse/ATMO-1093) (**it does not address the root issue described, which is the calculation of "instances" as relates to _instance state_) and part of [ATMO-1086](https://pods.iplantcollaborative.org/jira/browse/ATMO-1086).

Handled when time remaining is infinity for provider stats.

---

troposphere/static/js/components/providers/Instances.react.js
troposphere/static/js/models/Identity.js

[ATMO-1086](https://pods.iplantcollaborative.org/jira/browse/ATMO-1086) generally describes that _Troposphere UI_ is not displaying instance statistics accurately within the Providers view. This related to work done in #232 yet not limited to that. This pull request specifically addresses how we display the number of "instances consuming allocation" and a table with each allocation consuming instance. 
Previously, any instance that was *not* suspended was being treated as "consuming allocation":
```javascript
getInstancesConsumingAllocation: function (instances) {
var identityId = this.id;
return instances.filter(function (instance) {
if (isRelevant(instance, identityId)) {
return instance.get('status') !== "suspended";
} else {
return false;
}
});
}
```
source: …

Ensure only 'active' instances are included as "consuming allocation".

---

troposphere/static/js/components/admin/ResourceMaster.react.js
troposphere/static/js/stores/BaseStore.js

*Before:*
*After:*
This fix is bound to break other behavior. The main assumption our codebase
depends on:
fetchWhere leaves the stores models unaffected
prosif/cdosborn added these lines, so somewhere I assume we depend on the
behavior. I will investigate and add changes if I find them.

[ATMO-1122] Fix store populating models wrong

---

troposphere/static/js/components/common/InteractiveDateField.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js

The "Edit Image Version" modal was missing label text for the field that sets an "end-date" for the version (described in [ATMO-1132](https://pods.iplantcollaborative.org/jira/browse/ATMO-1132)). 
Change:  [Before](http://recordit.co/rx7fA7fCWj) => [After](http://recordit.co/GY7PgCleRE)

Added _expected_ label text for end-date field when editing image version information.

---

troposphere/static/js/components/MaintenanceScreen.react.js
troposphere/static/js/no_user.js

Was missing the "/" before the subpath to THEME_URL path in the following two files: 
troposphere/static/js/components/MaintenanceScreen.react.js
troposphere/static/js/components/MaintenanceScreen.react.js

fixed missing path slash for theme url refs

---

troposphere/static/js/AppRoutes.react.js
troposphere/static/js/bootstrapper.js
troposphere/static/js/public_site/bootstrapper.react.js

This is the first step to moving over to [ES6 Modules](https://babeljs.io/docs/learn-es2015/#modules) (notes from a discussion can be found [here](http://bit.ly/tropo-ui-es6)). 
The hardest files to managed & resolve **conflicts** are the 3 involved in this commit:
- bootstrapper.js
- AppRoute.react.js
- public_site/bootstrapper.js
Resources around understanding & using ES6 Modules can be found in the following gist:
- https://gist.github.com/lenards/711efb16001d02152598
The [next step](https://github.com/lenards/troposphere/tree/es6-module-imports/troposphere/static/js) will be to create a pull request for [es6-module-imports](https://github.com/lenards/troposphere/tree/es6-module-imports).

Changed to ES6 module syntax for entry points.

---

troposphere/templates/no_user.html

This fixes [ATMO-1139](https://pods.iplantcollaborative.org/jira/browse/ATMO-1139) by appropriately linking to the static image asset as _assets/resources/images_. 
This is not a "theme-ready" fix. See [lenards:atmo-1139](https://github.com/lenards/troposphere/tree/atmo-1139) for work on including `THEME_URL` in the `no_user.html` template (including changing in the django backend).

Correct source path for image assets (not theme-ready).

---

troposphere/static/js/actions/volume/update.js

Addresses ATMO-1116
Currently, when a user updates the name of a volume, the start date field in the UI updates to "Invalid date" as seen here:
This is a result of setting the updated Backbone model's attributes to be whatever is returned by the API after the PATCH, which is just the volume name and description. Without `merge: true`, this means that the local model only contains these two attributes, not the `start_date` that existed before the PATCH, leading to the "Invalid date" being displayed for the now nonexistent value.
Here is the result of setting `merge: true` when saving the Backbone model:

Fix volume update

---

api/models.py

This gets troposphere a step closer to safe operations with an empty initial database. 
When a `django.contrib.auth.models.User`, a `post_save` _signal_ is connected as a hook to `User` that will _get or create_ a user preference for that model ([api/models.py](https://github.com/lenards/troposphere/blob/55b1ee3f2fd462a3a44b58e57487b0841e15cab0/api/models.py#L61-L69)). 
This relates back to QA regression test failures discussed in [ATMO-1143](https://pods.iplantcollaborative.org/jira/browse/ATMO-1143).

Provide a `post_save` signal to ensure a User has preferences.

---

troposphere/static/js/actions/ProjectActions.js
troposphere/static/js/actions/VolumeActions.js
troposphere/static/js/actions/volume/destroy.js
troposphere/static/js/components/modals/instance/ExplainInstanceDeleteConditionsModal.react.js
troposphere/static/js/components/modals/instance/InstanceDeleteModal.react.js
troposphere/static/js/components/projects/detail/resources/tableData/volume/Status.react.js
troposphere/static/js/components/projects/resources/volume/details/sections/details/Status.react.js
troposphere/static/js/modals/instance/destroy.js
troposphere/static/js/models/Volume.js
troposphere/static/js/stores/VolumeStore.js

Color in the gif is off..
There is now an option to **Delete anyway**.  This fix prevents users from getting stuck where they cannot delete their instance because volumes are attached, and they cannot detach the volumes from
a borked instance. There were some changes to volume status to support this fix

Allow user to override instance delete

---

dev_requirements.txt
requirements.txt

This brings the Django backend and related dependencies up-to-date with [atmosphere:requirements.txt](https://github.com/iPlantCollaborativeOpenSource/atmosphere/blob/0dd7bea28a555b8017efd36349ab2a813653ffd6/requirements.txt).
In order to update `djangorestframework`, we will need to make changed to endpoints within `tropo-api/`.

Bring requirements up to date with atmosphere.

---

troposphere/static/js/components/NotFoundPage.react.js
troposphere/static/js/public_site/AppRoutes.react.js

Fixes [ATMO-1157](https://pods.iplantcollaborative.org/jira/browse/ATMO-1157). 
If you were on an authenticated/authorized routes (say, `application/projects/1/resources`) and your session expired, you would be presented with a blank page - with no context (written up as ATMO-1157). 
This pull request adds a "catch all" `Route` that will handle when this happens on the public site and display a contextual message (shown below) similar to other web applications when the resource/page is no longer viewable. 
This functionality becomes critical when you apply fixes regarding [ATMO-1160](https://pods.iplantcollaborative.org/jira/browse/ATMO-1160) & [ATMO-1024](https://pods.iplantcollaborative.org/jira/browse/ATMO-1024) _(which both deal with session aging, expiring & validation)_.

Provide _catch-all_ route for public site.

---

troposphere/static/js/actions/HelpActions.js
troposphere/static/js/components/modals/RequestMoreResourcesModal.react.js

**Depends on ATMO PR #102**
Send an `admin_url` parameter when making a POST to create a new resource request. This will allow the emails sent by Atmosphere to administrators to have a link to Troposphere's admin interface, instead of the Django admin interface the emails currently link to.

Send "admin_url" parameter when creating resource request

---

troposphere/static/js/components/common/InteractiveDateField.react.js
troposphere/static/js/components/images/detail/EditImageDetails.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js

Fixes [ATMO-1150](https://pods.iplantcollaborative.org/jira/browse/ATMO-1150). 
The styling & markup on InteractiveDateField was previous such that it has rendering quirks/issues (see below:
The modal is not the only place the component it is used: 
- `troposphere/static/js/components/images/detail/EditImageDetails.react.js`
- `troposphere/static/js/components/modals/admin/ManageUserModal.react.js`
- `troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js`
*Note:* `ManageUserModal` is currently not reachable within the _Admin_ user interface.

Address styling on Interactive DateField component 

---

troposphere/static/js/components/admin/ImageMaster.react.js
troposphere/static/js/components/admin/ImageRequest.react.js

Display better status text if there's an error with the request, enable resubmitting a rejected request, and disable resubmitting a closed request

Jetstream machine request fixes

---

api/admin.py
api/migrations/0003_transition_to_iplantauth_mod.py
api/migrations/0004_userpreferences_airport_ui.py
api/models.py
troposphere/static/js/components/Header.react.js
troposphere/static/js/components/Master.react.js
troposphere/static/js/components/images/ImageDetailsPage.react.js
troposphere/static/js/components/images/common/SecondaryImageNavigation.react.js
troposphere/static/js/components/images/detail/ImageDetailsView.react.js
troposphere/static/js/components/images/detail/ViewImageDetails.react.js
troposphere/static/js/components/images/detail/launch/ImageLaunchCard.react.js
troposphere/static/js/components/images/detail/versions/VersionsView.react.js
troposphere/static/js/context.js
troposphere/static/js/stores/ImageVersionStore.js
troposphere/static/resources/js/cf2/router.js
troposphere/static/resources/js/cloudfront2.js
troposphere/templates/cf2.html
troposphere/views/app.py
troposphere/views/emulation.py

This makes it so any unauthenticated visitor will land on the "Public Image Catalog" for a cloud: 
This relates to #247. Notably, it brings in a refactored/reworked version `troposphere/views/app.py` for handling requests, query string arguments, and associated response cookies. 
See JIRA tickets: [ATMO-1020](https://pods.iplantcollaborative.org/jira/browse/ATMO-1020), [ATMO-1021](https://pods.iplantcollaborative.org/jira/browse/ATMO-1021), [ATMO-1016](https://pods.iplantcollaborative.org/jira/browse/ATMO-1016), [ATMO-400](https://pods.iplantcollaborative.org/jira/browse/ATMO-400)

Introduce Public Image Catalog at landing page; Bugfixes for Troposphere as "Default UI"

---

troposphere/static/js/components/modals/volume/VolumeAttachModal.react.js
troposphere/static/js/components/projects/resources/instance/details/actions/InstanceActionsAndLinks.react.js
troposphere/static/js/models/Instance.js

Several functions were inlined. models/Instance could use more refactor.
When this commit was cherried onto master there was a conflict involving `shell_url` in:
troposphere/static/js/models/Instance.js

Prevent volume attach on non-active instances

---

troposphere/static/js/models/InstanceState.js

According to [InstanceState](https://github.com/iPlantCollaborativeOpenSource/troposphere/blob/master/troposphere/static/js/models/InstanceState.js), `'error'` is contained in the valid [final states](https://github.com/iPlantCollaborativeOpenSource/troposphere/blob/master/troposphere/static/js/models/InstanceState.js#L9-L16). However, when determine the percentage complete, `'error'` is not handled as a possibility: 
```javascript
var get_percent_complete = function (state, activity) {
// Number represents percent task *completed* when in this state
var states = {
'build': { /* ... */ },
'active': { /* ... */ },
'hard_reboot': { /* ... */ },
'reboot': { /* ... */ },
'shutoff': { /* ... */ },
'suspended': { /* ... */ },
};
// note - no `'error'` state above...
// 
// ... no case for when …
```

Include `error` as final state when determining percent complete for instance state

---

troposphere/static/js/components/dashboard/InstanceHistoryList.react.js
troposphere/static/js/stores/BaseStore.js

Currently, the instance history list doesn't show instance names. It also displays 100 items initially and the "load more" button has no effect.
The problem is in the current use of getAll() and fetchMoreWhere() in the component, coupled with the fact that fetchMoreWhere() is currently broken. Adding `remove: false` when fetching on an existing collection will add to the existing collection, which is what we expected fetchMoreWhere() to do in the first place. 
Before: ![beforefix](https://cloud.githubusercontent.com/assets/11079642/12991083/d2cd2ef4-d0ca-11e5-85c8-0768ff471c3b.gif)
After:

Fix instance history

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/collections/FunctionalCollection.js

In FunctionalCollection are a list of functions such as cmap, cfilter which
correspond to map, filter. It is now possible to chain these transformations
on a collection **without** wrapping the returned arrays with new Collection(..)
etc.
c.cmap(add1)
.cfilter(greaterThan1)
.csome(...)
....

Extend backbone with functions which return collections

---

troposphere/static/js/components/common/ProjectCreateView.react.js

QA lost it's selector when the cancel button class was changed from `btn-danger` to `btn-default` unique ID's were provided as better selectors.

Add ID's to buttons for QA

---

troposphere/static/js/bootstrapper.js

This fixes the issue where Collections lacked the cmap,cfilter,etc extensions.
Setting a Backbone.Collection to a new reference does not affect collections
whose prototype references the old Backbone.Collection, before being extended
with said functions.

Fix Bootstrap being extended at wrong time

---

troposphere/static/css/app/TabLinks.scss
troposphere/static/css/app/app.scss
troposphere/static/js/components/common/ui/TabLinks.react.js
troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js

**_(Edit: Ready for review)_**
This adds a set of Tabs to the top of the Select Image Step as part of the new Instance Launch Modal.  The tabs will filter the Images list to their respective category. 
**Tabs created:**
- Show Featured
- Show Favorited 
- Show All
**Reusable components created:**
- TabLinks.react (Renders a set of tabs representing items in a list passed as a prop)
- TabLinks.scss (The CSS used by TabLinks.react)
For the CSS in this PR I decided to switch to the [SUIT CSS](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md) naming convention. I realize I had started using [BEM CSS](https://en.bem.info/method/naming-convention/) in previous PR's and that this is confusing, but I feel strongly that this is the correct convention to use in our case. I can …

Featured Tab for Instance Launch ATMO-1213

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

This fixes the behavior, where `BasicInfoForm` was loading incorreclty.
open wizard -> select image-> close wizard -> open wizard -> select same image 
*stuff doesnt load
Now it loads :boom:

Fix store reload bug in Instance Launch Wizard

---

troposphere/static/css/app/media-cards.scss
troposphere/static/css/app/projects.scss
troposphere/static/js/components/projects/list/Project.react.js
troposphere/static/js/components/projects/list/ProjectList.react.js

This PR aims to improve on the grid structure of the project list and fix a bug when zooming out.
When zoomed out the grid would break because of some margin shenanigans. An inspection of the grid methods used, begged for a refactor because better solutions exist for grid layouts.
In this PR the media card layout was also used in place of the previous card styles. 
Note: The Bootstrap grid was used for this, against my preference, because that is the grid we have. All of our grids should employ the same grid system. If we decide to move to a new grid system, a refactor will be easier with this consistency.

Projects Grid Improvement ATMO-1236

---

troposphere/static/js/actions/ProjectActions.js
troposphere/static/js/actions/ProjectExternalLinkActions.js
troposphere/static/js/actions/ProjectImageActions.js
troposphere/static/js/actions/link/create.js
troposphere/static/js/actions/link/createAndAddToProject.js
troposphere/static/js/actions/link/destroy.js
troposphere/static/js/components/modals/link/ExternalLinkDeleteModal.react.js
troposphere/static/js/components/modals/project/ProjectRemoveResourceModal.react.js
troposphere/static/js/components/projects/detail/resources/ExternalLinkActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/ImageActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/ResourceActionButtons.react.js
troposphere/static/js/components/projects/resources/link/details/ExternalLinkDetailsView.react.js
troposphere/static/js/components/projects/resources/link/details/sections/ExternalLinkActions.react.js
troposphere/static/js/components/projects/resources/link/details/sections/ExternalLinkInfoSection.react.js
troposphere/static/js/modals/link/createAndAddToProject.js
troposphere/static/js/modals/link/destroy.js
troposphere/static/js/stores/BaseStore.js
troposphere/static/js/stores/ExternalLinkStore.js
troposphere/static/js/stores/ProjectExternalLinkStore.js
troposphere/static/js/stores/ProjectImageStore.js

Provide a method to remove Image and External Link from Project

---

troposphere/static/css/app/media-cards.scss
troposphere/static/js/components/modals/instance/launch/components/Image.react.js

There is a rare case when an Image can be left with no versions. This Image can not be launched, therefore we have to prevent the user from trying. A user might own the image or have seen it in another list, in this case hiding it could result in more tickets asking why the image is missing. Steve and I agree that showing the image however disabling it would solve both problems.

[Atmo-1241] Disable Images without versions in the Launch Modal

---

.babelrc
troposphere/static/js/components/common/ui/Button.react.js
troposphere/static/js/components/common/ui/Tooltip.react.js
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/components/modals/instance/launch/components/AdvancedOptionsFooter.react.js
troposphere/static/js/components/modals/instance/launch/components/BootScriptOption.react.js
troposphere/static/js/components/modals/instance/launch/components/InstanceLaunchFooter.react.js
troposphere/static/js/components/modals/instance/launch/steps/AdvancedLaunchStep.react.js

In this PR the Advanced Options Footer in the Instance Launch Modal has be redesigned so that the buttons better represent their actual behavior. 
What was the cancel button is now a "Restore to Default Options" button and includes a tooltip to communicate to the user what to expect as well as what has happened after it is initialized. 
What was the save button is now the "Continue To Launch" button. 
The "Advanced Options" button that takes the user to the Advanced options now indicates to the user that options have been changed by displaying a "check" icon next to it. 
Bootstrap (BS) uses the DOM for most of it's implementation, this is an anti pattern in React. For this reason in addition to several other anti patterns, we should be moving away from it. By creating our own reusable …

[ATMO-1211] Redesign of Advanced Footer

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

Fixes ATMO-1266
Simply won't add the script if it is already in the list.
A message "candybar" could be added to the modal for relaying messages to user.
In this case a message could be triggered in the event handler that lets the user know that they can't add the same script twice. 
Another place to use it would be to confirm that the advanced options has been reset. In [this PR](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/314)

Add condition if script is in list

---

troposphere/static/js/stores/BaseStore.js

Evaluate `options` before `options.clearQueryCache`
to prevent ref of undefined.

checking for options before 

---

troposphere/static/js/components/modals/instance/launch/components/ResourceGraphs.react.js

Fixes a miscalculation in the resource overview on the Instance Launch where 1GB should have been equal to 1024MB.

GB === 1024

---

troposphere/views/emulation.py

Use `settings.AUTHENTICATION_BACKEND` tuple to determine whether or not to redirect to a CAS client.
For clients that do *not* use CAS, redirect to `/application`.

Only use 'cas_oauth_client' if 'OAuthLoginBackend' is installed

---

troposphere/static/js/components/modals/SSHKeyUpload.react.js

A little research showed the possible ssh key prefixes
ssh-rsa, ssh-dss, ecdsa-sha2-nistp256, ssh-ed25519
This fix also tests to make sure that the key is either 3 or 2 words. Also,
the key/name are trimmed of white space.
While it is a little hard to tell, that confirm button is actually disabled.

Validate ssh keys

---

troposphere/static/js/components/modals/SSHKeyUpload.react.js

Now a message is displayed to help the user correct an error. It now detects
the following:
- incorrect key type
- erroneous newlines
- invalid characters (not encoded in Base64)
A short feature-film http://g.recordit.co/TUH5I2buFr.gif

Add further validation for ssh keys

---

troposphere/static/js/collections/SizeCollection.js
troposphere/static/js/components/providers/Instances.react.js
troposphere/static/js/components/providers/Resources.react.js
troposphere/static/js/components/providers/Stats.react.js
troposphere/static/js/models/Identity.js

If you do not hit `api/v2/size?archived=true`, then you will only get
the _active_ sizes (tiny1, tiny2, small1, medium, etc) for a cloud
(by the providers within a cloud).
So, if you are just looking at _active_ sizes, there is a possibility
that an instance's size is no longer available when fetching data to
show statistics or resource consumption, the number of that ilk.
This commit offers two improvements:
- leverage the fact that Atmosphere API does *not* delete things, it
merely end-dates them
- handle a situation when the 'size' for the Identity model is not
known (so be robust ... or dare I say _anti-fragile_)
One notion missing from this is the ability to communicate a statistic
is "uncertain" because of the failure to find the associated CPU or
memory for an instance. If …

Fix provider size lookup when calculating resource usage

---

troposphere/static/js/components/admin/ImageMaster.react.js
troposphere/static/js/stores/BaseStore.js

**DEPENDS ON ATMO PR 126**
Fixes a bug where images shown in the admin UI only display the user's own requests until clicking the refresh button if the user has loaded the "my requests page."
In addition, instead of fetching all of the image requests and filtering them in `render()` use the request filtering added to the API in Atmo PR 126. This means it no longer takes ~15 seconds to load image requests! Woo!

Fix image request bug

---

troposphere/static/css/app/layout.scss
troposphere/static/js/components/projects/common/ResourceDetail.react.js
troposphere/static/js/components/projects/resources/instance/details/sections/InstanceDetailsSection.react.js

This PR addresses [ATMO-1233](https://pods.iplantcollaborative.org/jira/browse/ATMO-1233). Expected behavior is that two clicks would select a word and three would select the line. When a user tries to select something in the instance details (either on the details page or the details side pane) like for example an ip address, since the label is on the same line it would be expected for convenience that two clicks would select a word and three would select the value like the IP not the label. 
However, in this case currently two clicks on the value selects the label plus the first word of the value, in this case numbers before the `-`, and three clicks selects both the label and the value. 
This PR makes it so that two clicks on the value selects the word without the label and three …

[ATMO-1233] resource details select behavior

---

troposphere/static/js/components/projects/resources/link/details/sections/ExternalLinkActions.react.js

This resolves a name discrepancy that prevented the delete button from working on the Project Link Detail page.

[ATMO-1302] Bug, Project Link delete button

---

troposphere/static/css/app/layout.scss
troposphere/static/css/app/utilities.scss
troposphere/static/js/components/projects/detail/resources/ButtonBar.react.js
troposphere/static/js/components/projects/detail/resources/ExternalLinkActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/ImageActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.react.js
troposphere/static/js/components/projects/detail/resources/ProjectDetails.react.js
troposphere/static/js/components/projects/detail/resources/VolumeActionButtons.react.js

This PR is a temporary resolution to [ATMO-1107](https://pods.iplantcollaborative.org/jira/browse/ATMO-1107). 
The action buttons above the project resource lists do not retain a proper layout on smaller viewports. 
This PR corrects this using bootstrap grid and a media query. The buttons now form three rows on small viewports. 
This is only meant to be an intermediate solution. There is a contextual disconnect between the buttons and the items the buttons are affecting. A better solution will be included in a proposed redesign of the page and how actions are associated with the items they affect.

[ATMO-1107] Fix proj resource action bottons for mobile

---

troposphere/static/js/actions/ImageRequestActions.js
troposphere/static/js/components/admin/ImageMaster.react.js

Delete leftover filtering from before it was added to the API, and don't redirect back to the admin list after resubmitting a machine request.

Machine request improvements

---

troposphere/static/js/components/common/ProjectCreateView.react.js

This PR resolves [ATMO-1248](https://pods.iplantcollaborative.org/jira/browse/ATMO-1248) by adding validation to the project Name field so that a user can't submit a new project with a name that exceeds the char limit on the backend. 
The limit on the API is around 250 some characters but we are validated for 60 on the client since longer titles could be problematic with layout in the UI. This can easily be changed in the `maxCharLen` variable.

[ATMO-1248] validate project names for max length

---

troposphere/static/js/components/projects/detail/resources/tableData/instance/Activity.react.js
troposphere/static/js/components/projects/detail/resources/tableData/instance/Size.react.js
troposphere/static/js/components/projects/detail/resources/tableData/instance/Status.react.js
troposphere/static/js/components/projects/detail/resources/tableData/volume/Size.react.js
troposphere/static/js/components/projects/detail/resources/tableData/volume/Status.react.js

This resolves ATMO-1014 where instance activity messages are lowercase.
In addition to the activity field, the other applicable fields were updated. The uppercase JS method on the instance status field was changed to the css solution as this converts all words to uppercase and is consistent with the other modified fields.

[ATMO-1014] Instance activity to uppercase

---

troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js

The Instance Launch Modal in the Select Image Step with the favorites tab selected, has the wrong message for the case where a user has no favorited images.
This PR adds the message "You currently have no favorited images" when the user has no favorited images.

[ATMO-1342] Add "no favorites" Message to Image Select Step in Launch Modal

---

troposphere/static/js/components/images/detail/versions/Version.react.js

The the version change log is not preserving line breaks included by the author when writing the change log. This is because the value is passed as a string. The showdown module is used to parse the string and wrap paragraph tags where line breaks are present. 
Since JSX would pass this new value as a string making the `<p>` visible in the browser, we use the `dangerouslySetInnerHTM` attribute. _(now i get why it exists 😄 )_

[ATMO-1314] Format version change log to preserve line breaks

---

troposphere/static/js/components/modals/link/ExternalLinkCreateModal.react.js

Added Asterisks and definition to Create External Link Modal to mark required fields.

[ATMO-1286] Including asterisks to indicate required fields

---

troposphere/static/js/components/dashboard/plots/ProviderSummaryLinePlot.react.js

Graph viewport and grid values now adjust to a value just over the highest value in the data set. This way if the user is over the limit they can see how much they are over while not having to show for example 150 if the highest value is 20.

[ATMO-1358] Fix Dashboard Resource Graph to show values over 100%

---

troposphere/static/js/actions/ProviderMachineActions.js
troposphere/static/js/components/images/detail/launch/ImageLaunchCard.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js
troposphere/static/js/components/modals/image_version/availability/EditAvailabilityView.react.js
troposphere/static/js/components/modals/image_version/availability/ProviderMachineEditItem.react.js
troposphere/static/js/components/modals/image_version/requirements/EditMinimumRequirementsView.react.js
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js
troposphere/static/js/stores/BaseStore.js
troposphere/static/js/stores/ProviderMachineStore.js

Prior to this commit, attempting to end date or un-end date a ProviderMachine would cause console errors.
After this commit, enabling and disabling of ProviderMachines works as expected:
**NOTE:**There was an error when 'saving' the image version (not the provider machines) at the very end of the video.. This was fixed in the final commit (75d50a6)

Allow enable/disable of ProviderMachines when using the "Edit Version" modal.

---

troposphere/static/js/components/modals/SSHKeyUpload.react.js

This is a small improvement to mirror github's ssh modal.
It seems the formatter has opinions about quotes that i'm not aware of.

Improve ssh key

---

troposphere/settings/default.py

This uses `settings.SESSION_COOKIE_NAME` to rename the session cookie for Troposphere and avoid clobbering by any subsequent responses following `api/v1/profile`.
See \[[ATMO-1366](https://pods.iplantcollaborative.org/jira/browse/ATMO-1366)\]

[ATMO-1366] Avoid session cookie clobber

---

extras/logrotate.troposphere
troposphere/static/js/components/modals/project/ProjectAddImageModal.react.js
troposphere/static/js/modals/project/addImage.js
troposphere/static/js/stores/ImageStore.js
troposphere/static/js/stores/ProjectImageStore.js

See [ATMO-1319](https://pods.iplantcollaborative.org/jira/browse/ATMO-1319).

ATMO-1319 Bugfixes for `add image to project`

---

extras/nginx/site.conf.j2
variables.ini.dist

Uses a variable, `ENABLE_HTTP2`, within `[nginx]` section to alter the `site.conf` produced. 
See [ATMO-1372](https://pods.iplantcollaborative.org/jira/browse/ATMO-1372)

Enable HTTP/2 module in Nginx site configuration

---

troposphere/static/js/components/modals/instance/InstanceImageWizardModal.react.js
troposphere/static/js/components/modals/instance/image/components/Tags.react.js
troposphere/static/js/components/modals/instance/image/steps/ImageInfoStep.react.js

Navigate to an active instance, click image, scroll to bottom of modal. `Tags` component loads after infinity seconds.
Now it loads properly. I abstained from formatting these commits/files to reduce conflict with later releases.

Fix tag component not loading

---

troposphere/static/js/actions/HelpActions.js
troposphere/static/js/components/Header.react.js
troposphere/static/js/utilities/userActivity.js

Using Intercom to note actions, we are looking to capture meaningful
actions in a way to guide usability & user experience design. This
is *not* just a clickstream of "events", but actions that help carry
out the completion of goals and provide an opportunity for support
staff to intervene/assist.
Detailed usage comments for `trackAction` are provided within the
module. Notable, `actionName`s should be a past tense verb joined
together with a noun by a delimiter:
- 'created-project', 'reported-instance', 'sent-feedback'
These actions can be used to segment and define a community cohort.

Define a utility function to track actions

---

.eslintignore
.eslintrc
.eslintrc.strict
.eslintrc.travis
.travis.yml
LINT.md
README.md
package.json

The main purpose of this PR is to improve linting. This should have no effect on `travis-ci`. But running `npm run lint` will produce errors. I think it would be good to keep _style_ stuff in `.esformatter` and _semantic_ stuff in `.eslintrc`. Because this doesn't break existing stuff it should be fine to merge in, and pr's can be made for meeting everyones preferences.
See [LINT.md](https://github.com/iPlantCollaborativeOpenSource/troposphere/blob/f37f04d64eb3ffabb4e848f91766c00ea686c3a1/LINT.md) for more thoughts.

Improve eslint

---

troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js

With React 0.14, they saw that when you got a DOM node from a ref
you were almost always manipulation that node,
```
this.refs.element.getDOMNode()
```
So, `this.refs.elements` is *now* the node element.
See commit 9c8ebcda2d6f32e0d0f612cc9ae322d1298e0e10

Change refs calls to remove getDOMNode()

---

troposphere/static/js/components/common/AUCalculator.react.js

Fixes the following console error:
```
Warning: validateDOMNesting(...): <th> cannot appear as a child of <tbody>
```

Fix "<th> cannot appear as a child of <tbody>" error

---

troposphere/static/js/components/modals/image_version/ImageSelect.react.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js
troposphere/static/js/components/modals/instance/image/components/VersionName.react.js

Allowing the user to avoid submitting a "valid form" only to receive an API conflict.
Example provided: ![Example Recorded](http://g.recordit.co/vVHPRaDhic.gif)
---
**NOTE:** The modal was not submittable because there was no description set for the version, and that is required in Troposphere.
**NOTE2:** I have commented out the `EditAvailabilityView` and replaced it with the Text `Coming Soon` because it rendered the `Advanced Option` portion of the screen inoperable. @cdosborn has volunteered to take a look at that as a bugfix for the P release.

Validate name when changing versionName or Image

---

troposphere/settings/default.py
troposphere/settings/local.py.j2

This pull request eliminates a warning related to changes in the Django Template from the 1.8 to 1.9 release. 
> If it sets TEMPLATE_DEBUG to a value that differs from DEBUG, include that value under the 'debug' key in 'OPTIONS'.
source: https://docs.djangoproject.com/en/1.9/ref/templates/upgrading/

Removed deprecated variable TEMPLATE_DEBUG

---

troposphere/static/css/app/common.scss
troposphere/static/js/components/projects/detail/resources/tableData/instance/Activity.react.js
troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js

Here are some important visual changes i've been meaning to include in the quasi-quail release.
@1765924 Apply no wrap to header like rows
**OLD:**
**NEW:**
@53ebecb Fix empty activity
**NEW:**
@4d03e32 Add whitespace exception for ssh key table
**OLD:**
**NEW:**

Small visual fixes

---

troposphere/static/js/components/Header.react.js
troposphere/static/js/components/modals/instance/InstanceDeleteModal.react.js
troposphere/static/js/components/projects/detail/resources/SelectableRow.react.js
troposphere/static/js/components/projects/detail/resources/tableData/instance/Name.react.js

It appears that we were previous depending on `instance.id` being `undefined` and the Instance.js model was altered such that a temporary _child_ identifier (`cid`) is now returned when accessing `instance.id`. 
Using the `get("<attribute-name>")` interface to the Backbone model appears to preserve the expectations.

Address instance link cid issue

---

troposphere/static/js/actions/InstanceVolumeActions.js

Currently in petrified-penguin, volume detach throws an exception:
```
InstanceVolumeActions.detach is not a function
```
The import was incorrect.
TODO
@lenards in prod i was able to successfully detach a volume through the api. It does not appear there is actually any issue with atmo.

Fix incorrect import for volume actions

---

troposphere/static/js/stores/AllocationStore.js

In production, volume create throws this exception:
"Uncaught TypeError: Cannot use 'in' operator to search for 'at' in undefined"
This PR fixes that error.

Fix store not updating, because incorrect event string

---

troposphere/static/css/app/header.scss
troposphere/static/js/components/Header.react.js

The Toggle was overlapping the user name as a result of absolute
positioning. Since the absolute positioning was intended to fix a layout
problem on smaller screens a different solution was used. This commit
also changes the color on the toggle switch and adds shadow.
_Note: although switching to inline styles is a future goal I think that the whole component should be moved over. In this case the Toggle would be moved to its own file and ALL of the CSS replaced. Since this is a temporary Component and only a small part was moved to inline, I decided it was easier to move back to CSS rather than be split between the two._

[ATMO-1406] Fix layout issue with Toggle UI

---

extras/nginx/locations/tropo.conf.j2
troposphere/settings/default.py
troposphere/settings/local.py.j2
troposphere/views/app.py

Now the theme can be managed by either nginx/django. Also, calling
`./manage.py collectstatic` takes care of the cf2 stuff that `make cf2` did.
I verified that this works for nginx. Given the settings on beta, this should just work.

Fix ./manage.py collectstatic

---

troposphere/static/js/components/images/list/ImageListView.react.js

Now, the text box always renders the user's raw input. Before the request is
passed to the stores, the query is trimmed. If the user searches: "apple_" and
"apple___", only a single request is fired for "apple".
TODO:

Allow space in images search

---

troposphere/static/js/components/projects/resources/instance/details/actions/InstanceActionsAndLinks.react.js

The feature providing a "zero-plugin" remote desktop via HTML5 (thanks to [noVNC](http://kanaka.github.io/noVNC/noVNC/vnc.html)) requires that the "Instance Detail" view within Troposphere only show the "link" when an instance *has* the _capability. 
*Web Desktop* _capable_ instances are indicated by the `v2/instances/:instance_alias` endpoint as follows:
```javascript
{
// ... snippet
"ip_address": "128.196.65.168",
"shell": false,
"vnc": false,
"web_desktop": false,
"identity": { /* ... */ },
// ...
}
```
>Note: the Remote Desktop link will appear, as well, for those who use a VNC plugin

Provide "Web Desktop" _link action_ only for noVNC capable instances.

---

troposphere/static/js/components/images/list/ImageListView.react.js

#420 didn't trim the query when it need to, also when I did trim I didn't make sure i was trimming a string object.
A subtle change is that the `getInitialState: query` is "" rather than null. That way we
can do:
var query = this.state.query.trim()
Rather than have to do:
// Make sure query is a string and has a trim method
if (this.state.query) {
query = this.state.query.trim()
}
Both "" and null are falsy.

Add trimming to input for all network requests

---

troposphere/static/css/app/layout.scss

Content wrapper was above the button blocking the event in Fire Fox on Ubuntu.
This sets the z-index above the blocking element

btn index to be above event blocking element

---

troposphere/static/js/AppRoutes.react.js
troposphere/static/js/components/Header.react.js
troposphere/static/js/components/dashboard/plots/ProviderAllocationPlot.react.js

- Don't show Provider views if using Allocation Sources 
- Title for Allocation Graph on the dashboard said "Provider Resources",
now it says "Provider Allocation"
**After Changes**
No Providers Link
Correct Title

Quasi Quail Final Tweaks 

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

The problem was the when the launch was selected from the image detail the version selected was the most recent, however from the project details the version selected was the fist version.
Before
After

fix wrong list item selector

---

extras/nginx/locations/tropo.conf.j2
troposphere/static/js/components/modals/allocationSource/NoAllocationSourceModal.react.js
troposphere/templates/allocations.html
troposphere/urls.py
troposphere/views/__init__.py
troposphere/views/allocations.py

For Troposphere installations using the _Allocation Source_ plugin, this adds a URL that is a landing page for community members that have a valid account without having an active/current allocation source to associated with running or new instances. 
This is an implementation done on short notice. Please offer ideas for improvement to be included as this is refined.

Handled valid account; no allocation case

---

troposphere/static/js/collections/AllocationSourceCollection.js
troposphere/static/js/components/common/ui/PercentageGraph.react.js
troposphere/static/js/components/dashboard/plots/AllocationSourcePlot.react.js

Was rounding to nearest int in both the tooltip and the graph label.
Also, was hiding the label when two graph bars were close to same length.
Both issues have been fixed, see screenshots. 
The problem was that the bar width was just under the width HighCharts will allow for two labels to show next to each other.

Fix dashboard graphs

---

troposphere/static/js/components/projects/detail/resources/SubMenu.react.js

This work adds CSS `id` attributes to the NEW resource menu within the _project resouces_ view along with specific `id`s for _NEW > Instance_, _NEW > Volume_, & _NEW > Link_. 
Reason: for a Selenium test, the ability to select by `id` improves the overall easy of writing tests.

Added static CSS `id`s to resource submenu

---

troposphere/views/allocations.py

The theme url got changed here: b94635567b8c1b53ccfc07d. But this template used the old theme url. 
This should prevent jetstream users from getting a themeless "You have an allocation source issue", once they're on a version with the new theme url.

Update path to theme

---

troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.react.js

This work removes the "Delete" resource button multiple resources are
selected in the ProjectDetail view.
Background:
-----------
Currently, we do *not* support a smooth "batch" delete interaction.
Prior to this commit, we deleted the _last_ selected resource. In
an effort to avoid confusing affordances, this is no longer visible
while buttons that can be used in "multi-select" remain (notable here
is "Move selected resources" - which is why the "checkbox"/multi-select
remains in the UI at all; otherwise, a simplification would be to pull
the checkboxes out altogether).
Future Work:
------------
The move to a MediaCard interface will present the opportunity to
address the topic of "Batch Actions" again. It is important that
we offer this is a manner that makes organization within Projects …

Altered if Delete resource button available

---

troposphere/static/js/components/modals/instance/InstanceDeleteModal.react.js
troposphere/static/js/components/projects/detail/resources/SelectableRow.react.js
troposphere/static/js/components/projects/detail/resources/tableData/instance/Name.react.js
troposphere/static/js/globals.js

An instance that is in "Build ..." status can be _selected_ and any following actions taken with that instance will fail because that model has that to be persisted via the API. This throws an uncaught exception when the action attempts to use the `this.props.resource`:
```
Cannot read property 'id' of undefined
```
We have seen at least 52 of these events experienced by 40 community members over the last 2 months. Given the general nature of the error - we cannot assume all occurrences are from this scenario. 
Also, following this error, children components may throw an error like: 
```
Cannot read property '_currentElement' of null
```

Select instance row fix

---

troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.react.js

This was a bit of silly mistake included in PR 460; the delete button
was _excluded_ for Instances when *that* Instance was in a _FINAL_
state. Final states are "Error", "Active", etc (complete list [1]).
Sanity prevails thanks to last minute testing :bomb:
[1] https://github.com/iPlantCollaborativeOpenSource/troposphere/blob/554dc3cd987d916c4772b7c1e5068c731d5acf5b/troposphere/static/js/models/InstanceState.js#L9-L17

Included Delete/"X" on single select resource

---

troposphere/static/js/components/modals/volume/VolumeAttachModal.react.js

Handled empty collection case when attaching volume.
If you have a volume within a provider that has no instances to 'target', then the previous handling of `...first().id` will result in an Uncaught Error.
Here are defaulting to `null`, and only allow the `id` of the first instance to be used when it is available to be _targeted_.
[see ATMO-1275](https://pods.iplantcollaborative.org/jira/browse/ATMO-1275)

Avoid "Uncaught Error" when attempting to attach

---

troposphere/static/js/components/projects/resources/instance/details/sections/InstanceInfoSection.react.js

If you click on the `<div>` containing the "gravatar" (whatever you've chosen) will output the information in the DevTools console in the following format:
```
<image-name> - <instance-GUID> - <provider> - <ip-address> - <deploy-date-time> 
```

Add a stealth way to collect uniform information about an instance

---

troposphere/static/js/actions/ImageVersionActions.js
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.react.js

- Fix error message to show the version name and error reported from the
API (This likely needs to be fixed elsewhere..)
- (Bugfix) Troposphere UI will let you update an image version with no
name, but the API fails.

Fix small UI bugs related to empty version name

---

troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js

Reported by community member @xuhang57, a malformed conflict resolution appear to create a rendering of the "Add SSH Key" elements. 
This pull requests removed those extra elements and returns the component to the expected rendering:
<details>
Full view of the user settings page after this fix was applied:
</details>

Removed extra elements within "Settings>SSH" Conf component

---

troposphere/views/emulation.py
troposphere/views/web_desktop.py
troposphere/views/web_shell.py

After making the changes below, web shell and web desktop are both accessible for staff users emulating regular users.

Fix emulation for Web Shell and Web Desktop

---

troposphere/static/js/components/dashboard/plots/AllocationSourcePlot.react.js
troposphere/static/js/components/dashboard/plots/ProviderAllocationPlot.react.js

The lack of a label for "no usage" was causing confusion for community members. This work uses a label & tooltip for this scenario.
See [ATMO-1525](https://pods.iplantcollaborative.org/jira/browse/ATMO-1525)

Show a label for "zero usage" scenario

---

README.md
extras/hooks/post-merge.hook

1) The readme had an incorrect command for installing 
2) The paths in the post-merge were based on the old hook directories

Fix hooks pointing to broken paths

---

scripts/fix_migrations.sh
troposphere/settings/local.py.j2

This is clean-up from the previous pull request (#398). The effort was to make the operation of Troposphere's `SECRET_KEY` generation mirror that of Atmosphere's `SECRET_KEY`. 
See [ATMO-1470](https://pods.iplantcollaborative.org/jira/browse/ATMO-1470).

Remove SECRET_KEY from settings

---

troposphere/static/css/app/applications.scss
troposphere/static/js/components/images/common/Bookmark.react.js

A class was mistakingly introduced to the bookmark star. This PR removes that class and associated styles. Also, since this is toggling an action not navigating the anchor was replaced with a span. 
The other half of ATMO-1562 is to add the identicon back to the detail page... 
I will be doing this in a different PR after I tackle other blocking issues.

ATMO-1562 fix star

---

troposphere/static/js/components/dashboard/plots/ProviderSummaryLinePlot.react.js

This work was partially done by @lenards in [this PR](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/480) 
The bottom graph was missed, now it is also happy
Before:
After:

ATMO-1560 add zero values to Provider Resources

---

troposphere/static/js/components/modals/instance/launch/components/ImageList.react.js
troposphere/static/js/components/modals/instance/launch/steps/ImageSelectStep.react.js

Resolves ATMO-1561 
The image list filters out End-dated images while the text representing the number of results did not. This caused the wrong number of items to be shown in the text.
Also, some space was added between the search field and results text to make it not suck.
Before
After

ATMO-1561 Filter list before handing to text

---

troposphere/static/js/components/images/detail/ViewImageDetails.react.js
troposphere/static/js/components/images/detail/removed/RemovedView.react.js

Part 2 of ATMO-1562 asked that the Glyphycon be put back on the Image detail page. This is a good idea as it helps connect the detail to the image clicked.

ATMO-1562 Part 2, Add Glyphycon

---

troposphere/static/js/bootstrapper.js

Steve had commented out the logic to show the "react maintenance screen" favoring the static maintenance screen during deploy because the react version was "all busted up". The import definition was still present causing our integration tests to fail. 
Since, Steve has decided that using the static maintenance is a better way to go, this PR is removing the related code so that other PRs against T-T can pass integration tests.

Remove unused code and comments related to Maintenance Screen

---

troposphere/static/css/app/applications.scss
troposphere/static/css/app/common.scss
troposphere/static/js/bootstrapper.js
troposphere/static/js/components/images/ImageTagsPage.react.js

This PR resolves ATMO-1570 
The Image Tag List was overflowing beyond the view port horizontally.
This PR also fixes some Typography issues and applies some general conventions established on the image search page.

ATMO-1570 Fix overflow issue, apply conventions

---

troposphere/static/js/components/modals/instance/InstanceDeleteModal.react.js

This PR resolves ATMO-1571 
The header on the DeleteInstance was using the wrong font size.
Also, changed the cancel button danger to default as cancel should be something a user feels safe to use.

ATMO-1571 fix delete instance header

---

troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js

This pr addresses: https://pods.iplantcollaborative.org/jira/browse/ATMO-1463
It is ready for review.
Here is the diff (the one below has highlight issues):
```diff
diff --git a/troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js b/troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js
index 3f6004b..bd53357 100644
--- a/troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js
+++ b/troposphere/static/js/components/settings/advanced/SSHConfiguration.react.js
@@ -97,13 +97,23 @@ export default React.createClass({
}, function() {});
},
+    style() {
+        return {
+            td: {
+                wordWrap: "break-word",
+                whiteSpace: "normal"
+            }
+        }
+    },
+
renderSSHKeyRow: …
```

Make SSH key names wrap, not overlap other content

---

troposphere/static/js/components/images/detail/versions/Version.react.js
troposphere/static/js/components/images/detail/versions/VersionList.react.js
troposphere/static/js/components/images/detail/versions/VersionsView.react.js

When reviewing the code, I noticed that the availability flag was being passed very far down, which was unneccessary (and it was only being used for this subview). It was removed, in preference of a test whether the user is logged in.
The code for detailView was broken into `summaryView` and `detailView`. The changelog was factored out.
When the card expanded in the public catalog, it would expand to an empty card. Now it displays a message:

Remove ambiguity in duplicate call to renderDetail 

---

troposphere/static/js/components/SplashScreen.react.js

We get excellent feedback from `raven-js` thanks to Sentry. But, we are missing _out_ on knowing which community member is experiencing that error. 
This pull request including the username & email for the community member in the error report provided via `raven-js`.

Improvement add context for Sentry error logging

---

troposphere/static/js/components/common/ui/Code.react.js
troposphere/static/js/components/common/ui/MediaCard.react.js
troposphere/static/js/components/images/detail/availability/AvailabilityView.react.js
troposphere/static/js/components/images/detail/versions/Version.react.js
troposphere/static/js/components/images/list/common/ImageListCard.react.js

The UUID was originally removed from the Version Card Summary as it was secondary information and detracted from the core information on the card. However, this UUID is used for troubleshooting and a user might be asked to provide it. 
This PR adds a detail view on the card by clicking it, revealing the UUID's in a new Code component for better readability. 
_Note: If we still want this to go onto S-S let me know and I can rebase and make a separate PR_ 
<details>
- All files touched change React class methods to use property short hand syntax ( this gives us named functions for better debugging and is easer to read). 
```
funcName: function() { ... }
// Is equal to  
funcName() { ... }
// Is equal to
let funcName = function() { ... }
funcName:  funcName
``` 
- Refactored `MediaCard` …

ATMO-1584 Add uuid to versions

---

package.json
webpack.config.js

Troposphere-ui can now be used with npm-link:
To check it out apply the following diff (after building/installing):
``` diff
diff --git a/troposphere/static/js/components/Master.react.js b/troposphere/static/js/components/Master.react.js
index 5bc03e1..99ac04f 100644
--- a/troposphere/static/js/components/Master.react.js
+++ b/troposphere/static/js/components/Master.react.js
@@ -7,6 +7,8 @@ import Header from "./Header.react";
import Footer from "./Footer.react";
import actions from "actions";
import modals from "modals";
+
+import { Loader } from "troposphere-ui";
import modernizrTest from "components/modals/unsupported/modernizrTest.js";
import NullProject from "models/NullProject";
import noAllocationSource from "modals/allocationSource/noAllocationSource.js";
@@ -130,6 +132,7 @@ …
```

Incorporate troposphere-ui with npm-link

---

troposphere/static/js/main.js
troposphere/templates/index.html
troposphere/views/app.py

Additionally, bring the configuration block from `js` to `python`

Use settings.DEBUG to decide if Sentry+Raven should be instantiated. 

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/components/modals/ExportCredential.react.js
troposphere/static/js/components/settings/AdvancedSettingsPage.react.js
troposphere/static/js/components/settings/advanced/ClientCredentials.react.js
troposphere/static/js/models/ClientCredential.js
troposphere/static/js/stores/ClientCredentialStore.js

This implements an advanced settings option to "Export Credentials" on a _per Atmosphere Provider_ basis to be used with CLI tools for the OpenStack APIs.
The credentials are provided for "Copy & Paste" into a shell script file that will _export_ the environment variables used by tools like [`openstack`](https://pypi.python.org/pypi/python-openstackclient) when sourced. 
This is a basic, "Phase 0", version of the feature.
See [ATMO-1457](https://pods.iplantcollaborative.org/jira/browse/ATMO-1457#comment-56950)
Textual _copy_ shown for each view within **details**:
<details>
</details>

Export credentials for use with client tools

---

troposphere/static/js/components/modals/ExportCredential.react.js
troposphere/static/js/models/ClientCredential.js

This pull request has 3 fixes in it:
- fix "width" issue for realistic values of `OS_PASSWORD`
- eliminate React warning about missing `key` prop on children within modal
- remove `debugger;` statement in credential model

Fix issues with "Export Credential" modal

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.react.js

The situation is this, someone deletes "Instance Name", tabs out of the field and moves on to other things. When they try to launch, it will *fail*. So, why not be a guardian angel and just _prevent_ them from entering into a situation that will lead to a failure?
That is the notion here.
If we have a `image` model, then get the name and fill it in for `instanceName`. If that is not available, just use some placeholder text that would be easy for a Cloud Operator to identify as having come from Troposphere.
See [ATMO-1595](https://pods.iplantcollaborative.org/jira/browse/ATMO-1595)

Ensure there is a value for "Instance Name"

---

api/models.py
troposphere/static/js/bootstrapper.js
troposphere/static/js/components/Header.react.js
troposphere/static/js/components/images/detail/header/HeaderView.react.js
troposphere/static/js/components/modals/ExpiredPassword.react.js
troposphere/static/js/components/projects/detail/resources/SubMenu.react.js
troposphere/static/js/context.js
troposphere/static/js/globals.js
troposphere/static/js/modals/ExpiredPasswordModals.js
troposphere/static/js/modals/expiredPassword/show.js
troposphere/static/js/models/Profile.js
troposphere/static/js/utilities/profilePredicate.js
troposphere/templates/index.html
troposphere/views/app.py

The CyVerse deployment of Atmosphere leverages Central Authentication Service [(CAS)](https://www.apereo.org/projects/cas) as a Single-Sign On / OAuth provider. But also, delegates to other authentication services within the system. These _delegated_ services can have rules differing from CAS, or may not be related to it directly. This is not only authentication option. Atmosphere uses [a module](https://github.com/iPlantCollaborativeOpenSource/django-iplant-auth) to provide CAS, OAuth, and Globus for given deployments (e.g. installations).
Validation rules outside of the authentication module can cause instance launch failures (i.e. the password for the delegated account has expired, but this fact is not known to the account-holder or community member). 
The reason for the failure needs …

Provide explicit indicators for when delegate system password expired

---

troposphere/templates/index.html

This fixes a syntax error in the `index.html`. I found it after my variables were not being set correctly in that file.

Add missing quotes around string

---

troposphere/static/js/components/modals/ExportCredential.react.js

When exporting OpenStack credentials, the API (or client) versions (so, v2.0 versus v3.0) require different environment variables to be exported from the `openrc` file. 
The `undefined` values can be seen in this [screen recording](http://recordit.co/YefkVYyAFX) at 0:08 elapsed. 
This was not handled in the previous pull request associated with ATMO-1457 (#508 / #509).

Filter out undefined environment variables

---

troposphere/static/js/components/images/list/ImageListView.jsx

Previously render only used get store methods, which never fetch and only read
if data has been fetched. This meant that prop changes (a new query) didn't
always cause data to be fetched.
Now when render gets called the data gets fetched if it's not there. Render
always gets called on mount or when a prop changes. This is simpler than
knowing that when a prop changes updateState gets called, and updateState
makes a network fetch.

Fix image search on tag select

---

troposphere/static/js/components/modals/ExportCredential.jsx
troposphere/static/js/components/settings/AdvancedSettingsPage.jsx

During the conflict resolution from `toco-toucan` to `undulating-umbrellabird`, the version of `troposphere/static/js/components/settings/AdvancedSettingsPage.jsx` from (then) master was included over `AdvancedSettingsPage.react.js`
This pull request takes the version from `toco-toucan` into U release.
In addition to bring back `<ClientCredential/>`, this also adds an "info" section to help ensure those using the client tools realize they need to take care to during if the OpenStack services are reachable.
And, a format issue with `OS_USERNAME` being on the generated "comment" line.

Include ClientCredentials component

---

troposphere/static/js/components/images/detail/availability/AvailabilityView.jsx
troposphere/static/js/components/projects/common/ResourceDetail.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/details/Alias.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/details/IpAddress.jsx
troposphere/static/js/components/projects/resources/volume/details/sections/VolumeDetailsSection.jsx
troposphere/static/js/utilities/clipboardFunctions.js

This uses the W3C Clipboard API functions added in #514 for _select_ resource details: 
- Instances (IP Address, Alias)
- Volumes (Identifier)

Add copy ability for select resource details

---

troposphere/static/js/components/modals/image_version/ImageVersionEditModal.jsx

Through inspecting error reports via Sentry, there are scenarios where the version of an image is undefined. When attempting to edit this field, an uncaught error is produced. 
This pull request protects against with the error (but in doing so, is **not** elegant about it).
One might consider this a [LoD](https://en.wikipedia.org/wiki/Law_of_Demeter) violation.

Avoid accessing undefined `id` property

---

requirements.txt
troposphere/settings/default.py
troposphere/settings/local.py.j2
troposphere/urls.py
troposphere/views/app.py
troposphere/views/auth.py
troposphere/views/emulation.py

This PR will bring django-cyverse-auth into the `voracious-velociraptor` release. The latest version that can be selected without code changes related to renaming in the library is 1.0.3

Cherry-pick of django-cyverse-auth

---

troposphere/static/css/app/app.scss

This PR overrides some bootstrap styling that caused problems with our User Menu on mobile views.
Normally I would not want to handle it this way but it is a highly specific selector that I doubt will cause trouble for anything else and the alternative is to implement a different User Menu that doesn't use the bootstrap classes. 
[ATMO-1608](https://pods.iplantcollaborative.org/jira/browse/ATMO-1608) suggested that the menu be opened by default. This PR fixes the main problem of the link text being the wrong color and the options being hidden unless you scroll. 
IMO, defaulting to open should only be done if we think there is an issue with users not finding the links under the User Menu. There is a cognitive cost to adding five more menu items to the initial navigation view.  If we do …

Fix User Menu on Mobile View

---

extras/logrotate.troposphere

Current logrotate file naming convention is not conducive to archiving.
Add a date to the end of the rotated files. (`dateext` option)
refs [#ATMO-1682](https://pods.iplantcollaborative.org/jira/browse/ATMO-1682)

Use date extension file naming for logrotate for easy archiving.

---

troposphere/static/js/components/images/detail/availability/AvailabilityView.jsx
troposphere/static/js/components/images/detail/versions/Version.jsx

Solution: Show 'End-dated' and 'No Availability' when version/image has been end-dated

Problem: Inconsistency with using end-dated flags (only being used on Image)

---

troposphere/static/js/components/common/Ribbon.jsx
troposphere/static/js/components/images/detail/ViewImageDetails.jsx
troposphere/static/js/components/images/detail/header/HeaderView.jsx
troposphere/static/js/components/images/detail/versions/Version.jsx
troposphere/static/js/components/images/detail/versions/VersionsView.jsx
troposphere/static/js/components/images/list/common/ImageListCard.jsx
troposphere/static/js/models/Image.js
troposphere/static/js/models/ImageVersion.js

This builds on the work of #542. 
An end-dated Image will appear with consistent "indicator". 
A `<Ribbon />` component is introduced to _generalize_ the use of "flagging" icons with indicator text (like, "End Dated"). And, this moves the approach for determining if an Image is _"end-dated"_ into the models for `Image` and `ImageVersion`. 
We also use `<Ribbon />` in all three scenarios (Image Detail, Versions within Image Detail, and Image Media Cards). 
See [ATMO-1698](https://pods.iplantcollaborative.org/jira/browse/ATMO-1698) & …

Problem: Image Details lack end-dated indicator; allows end-dated "launch"

---

troposphere/static/js/components/images/detail/header/HeaderView.jsx
troposphere/static/js/components/projects/common/SecondaryProjectNavigation.jsx
troposphere/static/js/stores/ProjectImageStore.js

The previously version of this functionality used ImageStore as a why to "join" the results of "image(s) for a project, by project.id". This gave the result a collection of `models/Image`. 
But, we can use the `/api/v2/project_images?project__id=:id` to satisfy "image(s) for project, by project.id", and we can construct `models/Images`s and return the collection to the caller as expected. 
Part of the root-cause for this is that the ImageStore caches queries for images by queryString. But, when you `ADD_PROJECT_IMAGE`, the cache-by-queryString is not invalidated. 
**Note:** this leverages `{ parse: true }` in the model will be construction. This means the model is created the same way that it is when returned via a response from the model (or collection) url.
See …

Problem: newly added images do not appear within projects

---

extras/logrotate.troposphere

Problem: Getting error messages like this:
```
error: error opening /var/log/celery/atmosphere-deploy_7.log: Permission denied
```
Solution: Change the structure of the logrotate config files back to what they
were and just have the `dateext` line added.

Fix logrotate permissions error

---

troposphere/static/js/components/images/detail/versions/Version.jsx

This fixes [ATMO-1710](https://pods.iplantcollaborative.org/jira/browse/ATMO-1710) where on version cards in the image detail, clicking on "edit" under version name wrongly opens the version detail. This is wrong because it could confuse users. 
To reproduce in V-V click "edit" below the version name and observe that the card expands.
Now on this branch do the same to verify that it doesn't expand but the edit modal is still triggered correctly.

ATMO-1710 Stop version card from expanding when edit is clicked

---

package.json
troposphere/static/js/components/common/ui/CopyButton.jsx
troposphere/static/js/components/images/detail/availability/AvailabilityView.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/details/Alias.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/details/IpAddress.jsx
troposphere/static/js/components/projects/resources/volume/details/sections/VolumeDetailsSection.jsx
troposphere/static/js/utilities/toastrHelpers.js

Resolves [ATMO-1725](https://pods.iplantcollaborative.org/jira/browse/ATMO-1725)
This was a change requested by Edwin.
Watching Edwin "discover" the clipboard feature on a version id. It became apparent that the current solution is confusing. Since there is no button the user attempts to highlight the image but the copy feature is triggered on click causing the highlighted text to drop and leaves the user uncertain if all of the text was copied.
Using a button will both inform the user of the feature and not block the text from being highlighted if the user wants to do that.
I ended up using a self contained component solution that accepts the text to be copied as a string propType over the current method of selecting the text in a target DOM node. I think this is an easier interface to …

Use Copy to Clipboard Button Over Clicking Text

---

troposphere/static/js/components/common/EditableInputField.jsx
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/components/BasicInfoForm.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/InstanceInfoSection.jsx

Add validation to instance name editing that prevents names ending
in a period followed by a series of numbers. Example: "name.2222"
In recent versions on OpenStack Nova, instance names that end with a period followed by any number of digits will cause a launch error in OpenStack Nova. A simple text validator should work on the launch dialog. If a user enters a name that matches this problematic pattern, the user should not be permitted to launch the instance and an error message should be presented to the user:
“Invalid format, names can not end in period followed by numbers. Example: “name.2222"”
This is linked to: https://iujetstream.atlassian.net/browse/JETSTREAM-139
See [ATMO-1777](https://pods.iplantcollaborative.org/jira/browse/ATMO-1777)
“Invalid format, names can not end in …

Problem: Instance name requires additional validation

---

troposphere/static/js/components/projects/detail/resources/tableData/instance/Size.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/details/Size.jsx

Prior an instance's size in details views would be looked up in the size store
which mirroed /api/v2/sizes. When an admin end-dates sizes, the sizes are no
longer at the api and correspondingly in the store resulting in a failed
lookup. Now troposphere just relies on the size information attached to the
instance.
Related jira: https://pods.iplantcollaborative.org/jira/browse/ATMO-1797
I end dated the sizes that my instances were referring and checked the following views.

Fix tropo to pull size information off instance, and not store

---

troposphere/static/css/app/footer.scss
troposphere/static/css/app/layout.scss

Footer should have `position = relative` on smaller screens.
If the footer is *not* relative, then it appears in a fixed width and is always visible (potentially occluding other components).
Note the presence of the footer element at the bottom.
The end result of merging is this view:
This reclaims the viewport to show as much of the content as possible.

Problem: footer override is not position correctly on mobile

---

troposphere/static/theme/README.md

Now that we have a new method for theming within Troposphere, we need to document how this works for new contributors.
This PR adds a `README.md` to the theme dir `./troposphere/static/theme` explaining how to modify the theme from within Troposphere without running [Clank](https://github.com/cyverse/clank).

Problem: Theme documentation missing from Theme directory

---

troposphere/static/css/app/footer.scss

This fixes a regression on master undoing work in [this commit](https://github.com/Tharon-C/troposphere/commit/cff8c06943e11efd77ca504cc54f4b8dc3601801)
The Support Button style in the footer was broken by a `line-height` property set on the footer.  
Typographic styles affect everything below the element they are applied to. Because of this it is best practice to set typography styles on the element you want to change using a class name.
In the case of the footer using `line-height` to manage the height of an element is not the way. Better to use padding or min-height as these only affect the element they are applied to and are flexible to the content within. In other words, zooming in or out the portal or changing font-size won't break the layout.

Problem: Regression, MUI Button style broken by footer line-height property

---

troposphere/static/js/components/modals/instance/image/components/Tags.jsx

This PR resolves [ATMO-1702](https://pods.iplantcollaborative.org/jira/browse/ATMO-1702)
When a user tries to create a new tag from the Create Image Modal the layout is broken as the "create and add" button overlaps the modal footer.
* The labels for the input fields were `span` tags. These were swapped for `label` tags and given the `htmlFor` attributes connecting them to the added input `id`s. This helps screen readers know what the input is for, since blind people can't see the relationship between the label and input. 
* The Bootstrap button was replaced with a MUI RaisedButton.
The `AddTag` select field is still focused when the `CreateTag` form is exposed. This keeps the user's attention in the wrong place. Better would be to move the focus the the description field. 
This is will …

Problem: Layout on Create Tag Step is broken and semantics are wrong

---

troposphere/static/js/AppRoutes.jsx
troposphere/static/js/components/SplashScreen.jsx

This resolves [ATMO-1564](https://pods.iplantcollaborative.org/jira/browse/ATMO-1564)
Non-staff shouldn't be able to see the admin page. 
However, if a non-staff user visits the admin URL path, the admin page will show. 
Instead, a "page not found" view should be shown id the user is non-staff.
`./application/admin`
`./application/admin`

Problem: Admin page can be viewed by non-staff through URL

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/collections/InstanceActionCollection.js
troposphere/static/js/components/common/InteractiveDateField.jsx
troposphere/static/js/components/images/detail/EditImageDetails.jsx
troposphere/static/js/components/projects/resources/instance/details/InstanceDetailsView.jsx
troposphere/static/js/components/projects/resources/instance/details/actions/InstanceActionsAndLinks.jsx
troposphere/static/js/constants/InstanceActionNames.js
troposphere/static/js/main.js
troposphere/static/js/models/InstanceAction.js
troposphere/static/js/public_site/main.js
troposphere/static/js/stores/InstanceActionStore.js
troposphere/static/js/stores/InstanceStore.js

This work changes `<InstanceActionsAndLinks ... />` from *hard*-coded to data-driven. It adds a new store to handle fetching "actions" for an _instance_ given the *current* status. 
It leverages the API endpoint `api/v2/instances/:alias/actions` (where `:alias` is a UUID).
When the status of an instance changes, the `InstanceActionStore` will receive that _dispatched_ change and react by fetching the latest "actions" available to that instance. 
See tickets: [ATMO-1413](https://pods.iplantcollaborative.org/jira/browse/ATMO-1413), [ATMO-1268](https://pods.iplantcollaborative.org/jira/browse/ATMO-1268), & [ATMO-1735](https://pods.iplantcollaborative.org/jira/browse/ATMO-1735)
Enables action on: [ATMO-1738](https://pods.iplantcollaborative.org/jira/browse/ATMO-1738)

Problem: instance actions are not driven by VM "status" 

---

troposphere/static/js/components/mixins/ChosenMixinExternal.jsx
troposphere/static/js/components/modals/instance/image/components/TagCreateForm.jsx
troposphere/static/js/components/modals/instance/image/components/Tags.jsx

Resolves [ATMO-1804](https://pods.iplantcollaborative.org/jira/browse/ATMO-1804)
When creating a new tag on the Create Image Request Modal. The focus stays on the search field rather than moving to the description field (the next field a user would want to fill). Because this field is a bit further down and there is no animation it would be easy for a user to not realize that a new form section was added, or at the least it is inconvenient. 
This PR moves the focus to the next empty field (the description field) so that the attention is in the right place, the screen scrolls down and the user doesn't have to grab the mouse. 
Testing this I became aware that the tags are not being added to the image after they are created like the button "Create and Add" suggests. This will be fixed in …

Problem: When creating a new tag focus stays on search field 

---

dev_requirements.txt

```
"Incompatible requirements found: appdirs==1.4.2 (from -r dev_requirements.txt (line 7)) and appdirs==1.4.0 (from \
-r requirements.txt (line 8))"
```
Solution: Reverted `dev_requirements.txt` to last known good version, then
regenerated it.

Problem: Ended up with inconsistent versions of `appdirs`

---

troposphere/static/js/components/projects/resources/instance/details/sections/details/Size.jsx
troposphere/static/js/models/Size.js

Changes in the Whimsical-Wyvern hotfix regarding how instances of `models/Size` were fetched introduced an issue with the appearance of size data on the Instance Detail view. 
The root cause was related to the model being created as a `new` instance, not fetched via a "store". This work eliminates the "visual" inconsistency with KB shown with the label of GB. 
There still is a conflict that remains in the codebase with how instances of `models/Size` are created.
<details>
An important detail with this work is that is addresses the issue without creating any more problems. The work done in #574 fixed the issue with Instance Detail view, but introduced problems with other occurrences of `models/Size`. 
Reported as [ATMO-1798](https://pods.iplantcollaborative.org/jira/browse/ATMO-1798)
Below …

Problem: memory shown in MB but labeled as GB

---

troposphere/static/js/components/modals/instance/image/components/Tags.jsx
troposphere/static/js/components/modals/instance/image/steps/ImageInfoStep.jsx

This PR resolves [ATMO-1701](https://pods.iplantcollaborative.org/jira/browse/ATMO-1701)
From the Image Request Modal, when creating a new tag it is expected after filling out the new tag form and clicking "Create and Add" that the new tag will be added to the list of tags for the image. Instead the tag is created but is not added to the list. 
The issues are that we are filtering the list for tags with "allow_access = true" yet this is handled on the server and the tag is optimistically added to the tag list so "allow_access" would be falsy. And the updateState method is blowing away our modified tag list when the store updates.   
This PR adds black list validation to the client so that optimistic updates to tags map more closely to the modals created on the server. (currently just …

Problem: "Create and Add" creates only, doesn't add

---

troposphere/static/css/app/app.scss
troposphere/static/css/app/cy-table.scss
troposphere/static/css/app/utilities.scss
troposphere/static/js/components/images/MyImageRequestsPage.jsx

This resolves [ATMO-1572](https://pods.iplantcollaborative.org/jira/browse/ATMO-1572)
The table on the My Image Request page should have a smaller headings font size and the rows should be cards. 
The status of the image request is communicated by changing the the whole row background color. While everywhere else we use "status lights"
The order of the information is very different from our other resources. 
ID's should have `CopyButton`s
- `cy-Table` component class as a temporary solution until we create a component for this use in Cyverse-ui. The name cy-Table was used because Bootstrap occupies the name `table`
- `u-noWrap` utility class as a convenience  to make the content stay on one line
- This table is not responsive so this work will be done in another PR possibly as a component …

Problem: "My Image Requests" table inconsistent with rest of app 

---

troposphere/static/js/components/common/ProjectCreateView.jsx

For the "Create New Project" modal, we have two elements that do not
have "name" attributes [0,1]. Having names on the form elements allows
them to be _targeted_ easily using `splinter` [2]:
```python
for key in context.browser.type('el-name', '..text..', slowly=True):
assert key
```
I also added `id` attributes to the elements because there are
`<label/>` that indicate they're "for" [3] the inputs, but without the
`id` I do not believe the associated is made.
Note, `htmlFor` is used by `<label/>` because *for* is a keyword in
JavaScript [4].
[0] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes
[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Attributes
[2] http://splinter.readthedocs.io/en/latest/api/driver-and-element-api.html?highlight=scr …

Problem: form elements difficult to target with testing tools

---

troposphere/static/js/controllers/NotificationController.js

This work fixes the juxtaposed appears of detailed "error messages" above the _summary_ title within error notifications. 
The `toastr` libraries methods for showing "notifications", (`error`, `info`, `success`, `warning`) accept arguments in the order:  `error(message, title, optionsOverride)`. This is likely because the `title` is optional. 
Here, message appears above title:
We may choose to alter appearance further with CSS, but this now has the _intended_ "title" appearing above the error message. _If desired, that should be done in an additional pull request._
For an example comparing the markup, please see **Details** below.
See [ATMO-1671](https://pods.iplantcollaborative.org/jira/browse/ATMO-1671)
<details>
</details>

Problem: error message appears as title

---

troposphere/static/js/bootstrapper.js
troposphere/static/js/components/requests/ResourceHistoryMaster.jsx
troposphere/static/js/utilities/subscribe.js

**TLDR:** This is a proposal for new way of adding listeners to stores, should just make it safer and easier to ensure a component doesn't encounter loading issues
**Example:** https://github.com/cyverse/troposphere/pull/561/files#diff-3df49258f0990fc6037016911f22d5bcR4
Whenever a component depends on data (makes calls to stores to fetch data), we
require the good habit of listening to stores, but nothing enforces that.
Many pages didn't listen to the stores on which they depend. They assume a
populated store. A full page refresh on the dependent page will reveal that
its not subscribed to the data. So the data comes back empty on first blush,
and they don't listen to the store for when the real data does arrive.
See [troposphere/static/js/utilities/subscribe.js](https://github.com/cdosbor …

Implement an explicit way to tie data to a component.

---

troposphere/static/js/actions/NullProjectActions.js
troposphere/static/js/actions/ProjectActions.js
troposphere/static/js/actions/instance/launch.js
troposphere/static/js/components/SplashScreen.jsx
troposphere/static/js/modals/instance/destroy.js
troposphere/static/js/modals/link/destroy.js
troposphere/static/js/modals/volume/destroy.js
troposphere/static/js/public_site/bootstrapper.jsx
troposphere/static/js/utilities/historyFunctions.js

Originally reported by @c-mart, the "transition" navigation following a "Launch Instance" is to an invalid URL that is **not** handled by the web server. 
So, before launch, the application is at "https://<host>/application/projects/3333/resources" and after launch it transitions to "https://<host>/projects/3333/resources" and is only _noticeable_ when you refresh.
To help understand the importance of this work being merged, here are the interactions that currently result in "transitions" to invalid URLs following the completion of the _action_:
- Launch Instance
- from Project Resource view
- Delete Instance
- Delete Volume
- Delete Link
- Delete Project
- Migrate resources
Recorded interactions of the failures will be provided in **Details** along with fixed interaction represented by …

Problem: some navigation code is not using "/application" basename

---

troposphere/static/js/components/help/HelpPage.jsx

When data is finally loaded into the HelpLinkStore, the <HelpPage/> component is not receiving the call to `updateState`.
This work does a forceUpdate on the page component.
Note: this page is a candidate for being converted to the `subscribe`
connector that Connor (@cdosborn) has written in PR 561 (recently
merge into master).
See [ATMO-1844](https://pods.iplantcollaborative.org/jira/browse/ATMO-1844)

Problem: data for "help" page does not load on initial view or refresh

---

dev_requirements.in
dev_requirements.txt

This updated `ipdb` to `0.10.2` in _dev_requirements.txt_.
Also, it removes the _"pinning"_ present in `dev_requirements.in` (which seems to be an anti-pattern for projects managed by pip-tools). 
When authoring `behave` tests, I was attempting to set a breakpoint for `ipdb` and caught hitting the following error:
```
AttributeError: 'TerminalInteractiveShell' object has no attribute '_eventloop'
```
Digging around, it appeared that `ipdb==0.10.2` did not have this issue (see [ipdb issue 105](https://github.com/gotcha/ipdb/issues/105)). 
Thank you to @julianpistorius for the assignment.

Problem: dev requirements pinned and do not state ipdb latest

---

troposphere/static/js/stores/InstanceStore.js

The issue is that deleting an instance emits a change to the InstanceStore, but ProjectDetails (which displays a user's instances in a table) doesn't listen for updates to that store. Rather, it listens only to theProjectInstanceStore.
My intention is to follow this fix with a larger fix if time warrants.
Related issue, #583 
Related jira, [ATMO-1479](https://pods.iplantcollaborative.org/jira/browse/ATMO-1479)

Fix UI ignoring instance delete

---

troposphere/static/js/actions/InstanceActions.js
troposphere/static/js/actions/instance/shelve.js
troposphere/static/js/actions/instance/unshelve.js
troposphere/static/js/components/modals/instance/InstanceShelveModal.jsx
troposphere/static/js/components/modals/instance/InstanceUnshelveModal.jsx
troposphere/static/js/components/projects/detail/resources/tableData/instance/Status.jsx
troposphere/static/js/components/projects/resources/instance/details/actions/InstanceActionsAndLinks.jsx
troposphere/static/js/modals/InstanceModals.js
troposphere/static/js/modals/instance/shelve.js
troposphere/static/js/modals/instance/unshelve.js
troposphere/static/js/models/Instance.js
troposphere/static/js/models/InstanceState.js

This work adds the necessary components & actions for two operations (or one symmetric):
- Shelve
- Unshelve
"Shelving" instances is the best way to _free up_ resources on a provider without an outright deletion. Some operators have been shelving unused instances to reduce resource utilization. However, the owners of instances would have to contact the operators to get access to the instance. 
> Also, the changes here will indicate "inactive" instances as a "gray" dots. This is not _just_ for "Shelved_offload", but also "Shutoff" & "Suspended". We may wish to use a "calming" color to communicate a favorable decision (e.g. encourage "shelving") and an "agitating" color for operations that are less favorable.
**Note:** this used two Glyphicons to communicate _putting an instance on a shelf_ …

Problem: cannot shelve/unshelve instances within capable providers

---

troposphere/static/js/components/images/common/Bookmark.jsx

Bookmark on image detail was not updating. Probably related to the work done on react router upgrade. 
This PR uses @cdosborn `subscribe` HOC to update the bookmark component when the store changes.

Problem: bookmark on image detail not updating

---

README.md
extras/nginx/locations/tropo.conf.j2

This pr lays out how to setup webpack-dev-server. My previous setup was jenky, and some of the assets didn't load. This is short and much nicer.

Add instructions for webpack dev server

---

troposphere/static/js/components/modals/RequestMoreResourcesModal.jsx
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/modals/help/requestMoreResources.js

Resolves [ATMO-1784](https://pods.iplantcollaborative.org/jira/browse/ATMO-1784)
In some circumstances, like when a user is trying to launch an instance, if the user is over resource limit or will be for a particular Provider, the user is given the chance to request more resources. It is a reasonable expectation that in the Request Modal presented to the user, the provider they are requesting for is already populated. Instead the provider is set to the first in the collection. This is awkward and could lead to requests being made to the wrong provider. 
Now when the user is requesting in the case described, the expected provider is set as default.
Shows that whatever provider selected on Instance Launch Modal is default on RequestResource modal
Shows that the default provider otherwise is …

Problem: Request more resources modal doesn't default to a provider when expected

---

troposphere/templates/login.html
troposphere/views/maintenance.py

Sometimes a maintenance record wants to have new lines. It is more useful to use `\n` for this. Because HTML doesn't respect `\n` we need to replace this with `<br/>` before rendering in our template.  
_Note: that I removed the check for `record.provider` because it seems like dead code. With my best efforts I can't see that it exists in the model. If we want to account for `record.provider` and I am missing something then [this branch](https://github.com/Tharon-C/troposphere/tree/ATMO-1863-if-provider) can be used instead._
Shows that the middle message containing `\n` has spaces where desired. 
shows the `<br/>` added to the markup

Problem: Maintenance messages do not persist in new lines (\n) in render

---

troposphere/static/js/components/projects/detail/resources/ButtonBar.jsx
troposphere/static/js/components/projects/detail/resources/ExternalLinkActionButtons.jsx
troposphere/static/js/components/projects/detail/resources/ImageActionButtons.jsx
troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.jsx
troposphere/static/js/components/projects/detail/resources/VolumeActionButtons.jsx

The group of batch action buttons on the project resource page wrap awkwardly at reasonable desktop widths. 
This is a temporary solution until we have a dedicated batch action bar that keeps all of the buttons in one wrapper. It's better but still pretty bad. :(
_Note: Since the styles are repeated several times, it would seem to be better to make this a class or component. However, since this is temporary, the styles are inline. This way, removing later will be easier because the code is bound to the component where class declarations are not and harder to delete with confidence._
Shows that buttons on the right collapse 
Shows buttons on the right move below first group
This is a temporary fix

Problem: project resources looks awkward at medium screen sizes

---

troposphere/static/js/components/images/ImageDetailsPage.jsx
troposphere/static/js/stores/ImageStore.js

This resolves [ATMO-1771](https://pods.iplantcollaborative.org/jira/browse/ATMO-1771)
If a user visits an image detail directly, for example from a link provided in an email, if that image doesn't exist or is not permitted the page shows an infinite spinner. Instead we want to show a 404 page.
The solution here deals with the fact that are current models are null until we have a valid model returned from the server. Because of this there is no way to tell if we are still fetching or the response was 404. 
To get around this a new method was added to return a model with a status of 404 if that is the case. Since many areas are affected by the image store and we will hopefully soon have something better than the  "null pattern" this was the least invasive approach.
Captured in …

Problem: Image Detail Pages doesn't let the user know if Image is 404

---

package.json
troposphere/static/js/components/NotFoundPage.jsx
troposphere/static/js/components/images/ImageDetailsPage.jsx
troposphere/static/js/utilities/str.js

Resolves [ATMO-1877](https://pods.iplantcollaborative.org/jira/browse/ATMO-1877)
We have a PageNotFound view that should be used in places that the current message isn't as appropriate as it could be. For example, PageNotFound has a prompt message to login that is inappropriate if the user is already logged in. Also, the message states that the 'page' can not be found which is ok but could be more specific. For example, trying to view an 'image' detail it could state that the 'image' is not found.
This PR only shows the login prompt if **not** logged in and allows to optionally pass a `resource` prop to change the default value `"page"`.  See screenshots. 
Shows the default behavior of `PageNotFound` when **not** logged in and **no** `resource` prop set. 
* The login message is visible
* …

Problem: NotFoundPage isn't reusable in most cases

---

troposphere/static/js/actions/instance/launch.js

This work increases the resilience of the _tracking_ the progress of launched instances. It does this by adding a handler for failure when looking up an instance via the Atmosphere V2 API.
During the mock deployment of yampy-yellowlegs, running [Operation Sanity](https://github.com/cyverse/operation-sanity) produced the observation that newly launched instances appeared to be _stuck_ in the "Build" status. 
Unfortunately, the code that dispatched for status polling was not being executed. It turned out that a subsequent call to the `api/v2/instances/:new-instance` was returning a "404 Not Found" even though the call was made within a "success" handler for the instance's creation (though, the creation happen via `api/v1/...`). 
This code could be implemented using a `.fail(...)` chained …

Problem: Instances within Project View appear "stuck" in Build

---

troposphere/templates/login.html
troposphere/views/maintenance.py

This work removes the "replace_*" methods added in #603 and leverages already available template filters provided by Django (see [linebreaksbr](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#linebreaksbr)).
- commit 1eaebec - restores the assumption that `records` is a [`QuerySet`](https://docs.djangoproject.com/en/1.10/ref/models/querysets/)
- commit 7d6bf56 - favors the usage of [builtin template filters](https://docs.djangoproject.com/en/1.10/ref/templates/builtins) provided in Django
Note: `linebreaksbr` is used over [`linebreaks`](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#linebreaks) because `linebreaksbr` does not surround the result in _another_ block-level element (in this case, `<p/>`).
We are choosing this options for three reasons:
1. the …

Problem: newline translation to breaks adds code / breaks assumption

---

troposphere/static/js/components/admin/ImageRequest.jsx

This work uses the `subscribe` Higher-order Function to gain the default "forceUpdate" on emit change behavior. 
The issue appears to be related/created by the changes made during `react-router` upgrade. The `<Master />` component as the parent to all components was receiving "emit change" and causing components to re-`render`. With the upgrade, that (potential) _accidential_ behavior was no longer present.
_Note: this is targeting Yampy-Yellowlegs so that it will be included in the forthcoming release to Jetstream._

Problem: Image Requests not updated as status changes

---

troposphere/static/js/components/admin/ImageRequest.jsx

This work uses the `<ShowMoreEllipsis />` from `cyverse-ui` in a "clickable" context to allow for "collapsing output". 
This introduces two components within the "ImageRequest.jsx" that could be refined and extracted at a later time. 
The `<Code />` is essentially "source" copied from the CyVerse-UI Style Guide. It is not exposed as an _"import"-able_ component. 
This depends on #621 being merged first (as it extends the version of `<ImageRequest />` defined in that pull request.
<details>
</details>

Problem: Exception messages in Image Requests are distracting

---

troposphere/static/js/components/modals/volume/VolumeCreateModal.jsx

I might be wrong. But from my perceptive, the intention here is trying to use a CSS class called `classNames`. We do have a 'classNames' than can be imported but I think that's probably not something fits here?

Problem: typos exist on html attributes (className used when classNames intended)

---

dev_requirements.txt

CI indicates that we have double requirements for Django version. This patch fixes the problem. Please let me know if the intention is to use Django `1.10` 🔢

Problem: fix the double requirements of django

---

dev_requirements.in
dev_requirements.txt
requirements.in
requirements.txt

Correct *requirements.in specifications
Add unlisted markdown dependency (django-rest-framework)
In a larger feature, I'm going to implement the improved solution for *.in files and add docs to make it crystal clear :crystal_ball:.

Fix broken upgrade to django 1.11

---

troposphere/views/exceptions.py

Within this file, `status` never gets imported. This patch adds the missing lib.

Problem: missing "status" causes a server error

---

troposphere/static/js/components/modals/instance/launch/steps/SizeSelectStep.jsx
troposphere/static/js/components/modals/project/CantMoveAttachedModal.jsx
troposphere/static/js/modals/UnsupportedModal.jsx

As noted in #625 by @xuhang57, we had a couple of typos for the attribute name used to JSX syntax for including CSS classes. 
This work corrects the remaining occurrences of this typo _pattern_ within the codebase.
It appears these incidents might have been caused by a "replace string" operation gone awry. All of the occurrences found were for the `t-body-2` class.
```
<h4 className="t-body-2">
```
- ~[ ] New test(s) included to reproduce the bug/verify the feature~
- ~[ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~

Problem: typos exist in HTML attribute name for CSS class

---

troposphere/static/js/components/dashboard/InstanceHistoryList.jsx

The _identifier_ used to determine the icon for _Instances_ within the Instance History was not the valid identifier for `models/Instance`s. It was the `client ID` for the Instance History item. 
This work corrects the identifier used as input to the hash function (done in commit 2d47f74c5bddaee79c5ec6d8d05addd6e287908b, for clarity review this first).
It also does a "rename" refactor on the function that produces the rendered JSX components for `<InstanceHistoryList />`. The previous version recreates confusion by _improperly_ overloading the term "instance".
See [ATMO-1848](https://pods.iplantcollaborative.org/jira/browse/ATMO-1848)
<details>
</details>

Problem: Gravatar icons for Instances not consistent across views

---

troposphere/static/js/components/admin/AtmosphereUser.jsx
troposphere/static/js/components/admin/Emulate.jsx

The _emulation_ feature has been obscure from view - but known amongst the team. This work would define a compact, clickable component to perform the `emulate` action for a community member within the "Admin > Atmosphere Users" section of the administrative user interface.
See also [ATMO-1602](https://pods.iplantcollaborative.org/jira/browse/ATMO-1602)
<details>
</details>

Problem: no easy way to emulate a community member

---

package.json
troposphere/static/theme/theme.json.j2
troposphere/templates/error.html
troposphere/views/app.py

- Provide a new template, `error.html` that will handle resources that are not built by webpack.
- Right now, `/assets` is expected to follow the logic as set-out in `extras/nginx/locations/troposphere.conf`, this will work. But if you are using `webpack-dev-server` you will see an ugly screen.
- Possible solution to the problem above might be: Creating another location `/unbundled_assets` that will always point to the `/assets` directory, to be pointed to _only_ by `error.html` and keep separate from the `/assets`  managed by webpack-dev-server.

Problem: Failure to load webpack (because webpack is compiling/failed to compile) causes 500

---

extras/nginx/site.conf.j2

Include nginx snippet to block calls with an invalid host header.

Bugfix: invalid HTTP Host header causes 500

---

troposphere/static/js/components/common/ui/SelectMenu.jsx
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourcesForm.jsx

Solution: Disable sizes when too small to launch an instance.
- Use custom element-to-option rendering for providerSizeList
- Filter down available providerSizeList based on new API value, size_gb
- Select a new providerSize if the previously selected size is not
available.
Atmosphere: https://github.com/cyverse/atmosphere/pull/397

Problem: Disk sizes are not validated on the client-side

---

troposphere/static/js/components/projects/detail/resources/image/ImageTable.jsx
troposphere/static/js/components/projects/detail/resources/instance/InstanceTable.jsx
troposphere/static/js/components/projects/detail/resources/link/ExternalLinkTable.jsx
troposphere/static/js/components/projects/detail/resources/volume/VolumeTable.jsx

When using integer identifiers from the database, you can have unintended "collisions" between identifiers for different models. Here we leverage the available "alias" identifier to avoid any "collision", and subsequent "double selection" [\[0\]](https://pods.iplantcollaborative.org/jira/browse/ATMO-1320).
Note, these aliases, "uuid" in the model attribuates, are UUIDv4 [\[1\]](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29) and collisions are extremely unlikely, it's "at least one collision is 2.71 quintillion" [\[2\]](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions). We can operate as if there is a guarantee of uniqueness.
\[0\] https://pods.iplantcollaborative.org/jira/browse/ATMO-1320
\[1\] …

Problem: integer IDs can lead to selecting/unselecting collisions

---

troposphere/static/js/components/projects/resources/instance/details/actions/InstanceActionsAndLinks.jsx

This includes any activations of the "Web Shell" remote access action.
The approach for including and activating the Gate One remote access
technology so we can properly evaluate the community adoption of this
when compared with the new/beta technology: Apache Guacamole.
This is a transplant of @lenards https://github.com/cdosborn/troposphere/pull/6. It was based against a branch that was rewritten an brought into zesty-zapdos, so I reproduced it here.

Included actions to track when activated (2)

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx

A provider size of 0 means that Openstack will match the disk size of the image, being launched for that size. 

Add special case for provider size of 0

---

.eslintrc
LINT.md
troposphere/static/js/AppRoutes.jsx
troposphere/static/js/components/common/ui/Button.jsx
troposphere/static/js/components/common/ui/CopyButton.jsx
troposphere/static/js/components/help/HelpPage.jsx
troposphere/static/js/components/images/MyImageRequestsPage.jsx
troposphere/static/js/components/images/detail/versions/VersionList.jsx
troposphere/static/js/components/modals/instance/InstanceImageWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/components/BasicInfoForm.jsx
troposphere/static/js/components/modals/instance/launch/steps/LicenseStep.jsx
troposphere/static/js/components/modals/instance/launch/steps/SizeSelectStep.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/AllocationSourceSection.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/InstanceInfoSection.jsx
troposphere/static/js/components/projects/resources/instance/details/sections/metrics/GraphController.js
troposphere/static/js/stores/BaseStore.js
troposphere/static/js/stores/ProjectInstanceStore.js

This work resolves a number of `eslint:recommended` violations:
- no-extra-semi
- no-unused-vars
- no-extra-boolean-cast
- no-redeclare
This would allow:
- comma-dangle
And, it treats `console` statements as warnings.
The results of merging this would be enabling `"eslint:recommended"` rules, plus our existing `.eslintrc` definition.
Note: I have "disable" a violation for one issue related to removing licenses from an imaging request. This has been captured within [the product's internal issue tracking](https://pods.iplantcollaborative.org/jira/browse/ATMO-1962) (noted within commit 7d39a6c).

Problem: do not apply a recommended set of ESLint rules

---

troposphere/static/js/components/modals/instance/launch/components/ResourcesForm.jsx

This uses `featureFlags.hasProjectSharing()` to determine if the "form-group" for identity needs to be included in the <ResourcesForm/>.
We have merged Project Sharing (aka User/Group Mapping) into the mainline to avoid "drift". We know this feature will take multiple releases before it can be enabled within a production deployment.
Our intend is to make Project Sharing something that can be "toggled" on, or enabled - then development can enhance the feature without it falling behind the master branch (e.g. trunk). This concept has been discussed in a way places [0,1] (usually ThoughtWorks folks [2])
This work is part of what needs to be fixed in master before a release branch for the A-A (2017) can be cut.
[0] https://trunkbaseddevelopment.com/
[1] …

Problem: Identity dropdown appears when Project Sharing disabled

---

README.md
webpack.config.js

This PR modifies the webpack config to support developing on a remote server with ssl support.
The default command to run the webpack server is `npm run serve`, which boots up the webpack dev server on `http://localhost:8080`. This works fine when developing on a laptop via localhost, but doesn't support the development flow of operating on a remote machine, such as `https://server.example.org`.
This PR modifies the webpack config to support overriding the variables necessary to support the remote ssl flow.
Instead of running `npm run serve`, you can now do this:
```
npm run serve --
--env.host=server.example.org
--env.port=8080
--env.https
--env.sslKey=/path/to/ssl/server.example.org.key 
--env.sslCert=/path/to/ssl/server.example.org.crt
```
This will boot the webpack development server …

Setup webpack for remote ssl

---

troposphere/static/js/components/admin/ImageRequest.jsx

This is another "handle undefined & null" still helper, or utility method. I think this ought to be a utility given the complexity of the format for Instance Size(s). I did waffled on whether to destructure the `size` model to remove the repeated `{$size.attr}` without the
string template literal. It might be a waste of defining local variables for something like this, so if desired - those could be inlined.
See also [ATMO-1754](https://pods.iplantcollaborative.org/jira/browse/ATMO-1754)
- ~[ ] New test(s) included to reproduce the bug/verify the feature~
- ~[ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~

Problem: creating instance size label results in error

---

troposphere/static/js/components/admin/ImageMaster.jsx

This is another defensive change to accessing model attributes. Here we want to handle when `request.get("new_machine_owner")` may be `undefined`.

Problem: accessing potentially undefined model attribute

---

troposphere/static/js/components/modals/instance/image/steps/ImageInfoStep.jsx
troposphere/static/js/components/modals/volume/VolumeReportModal.jsx
troposphere/static/js/utilities/capture.js

Here, we mean "safe" in that an attempt to `.get("href")` will not result in an error.
An error relates to the help link missing was observed [0]. In this commit, we favor the "empty" document fragment [1], so this may pop the to the top of the viewport. But, it will not cause an unhandled error.
[0] https://pods.iplantcollaborative.org/jira/browse/ATMO-1752
[1] https://www.w3.org/TR/html5/browsers.html#scroll-to-fragid
Addresses the following internal tickets:
- [ATMO-1752](https://pods.iplantcollaborative.org/jira/browse/ATMO-1752)
- [ATMO-1753](https://pods.iplantcollaborative.org/jira/browse/ATMO-1753)

Problem: retrieving help link can cause error

---

README.md
webpack.config.js

**Problem:**
Dev environments show unstyled "Loading Atmosphere"
**Solution:**
Load css before js like in prod making hot reloading css an opt-in feature
CSS hot reloading requires the css to be shipped in the js bundle. That means
that our html will show unstyled content, until the js bundle is loaded. This
results in a white page with black text:
Loading Atmosphere
This will never happen in production, because we ship the css in a link tag
in the head of the document, forcing the css to be applied before the content.
In an effort to bring the developer experience closer to production, we are
making CSS hot reloading opt-in.
In order to enable it, prefix your npm run serve command like so:
```bash
CSS_IN_JS=true npm run serve ...
```

Problem: Dev environments show unstyled "Loading Atmosphere"

---

troposphere/static/js/components/projects/resources/instance/details/sections/details/IpAddress.jsx

The helpful "copy" hyperlink button is shown when an Instance is without an IP address. 
This work will only hide `<CopyButton />` when an IP is not applicable (aka invalid). It will show for floating and fixed IP addresses.
<details>
Here is the interaction that we are addressing:
http://g.recordit.co/rn45LezrcJ.gif
</details>

Problem: Copy Button appears next to invalid IP Addresses

---

troposphere/static/js/components/common/EditableInputField.jsx

**Problem:**
EditableInputField threw exception if onChange prop didn't exist
**Solution:**
Don't require onChange prop if its not necessary
**Explanation:**
This resolves an issue where editing the volume name in the volume details threw an exception. EditableInputField was calling props.onChange when it the handler was never provided, and VolumeDetailsPage didn't need to listen onChange.

Provide noop onChange handler, when not supplied by user

---

troposphere/static/js/components/projects/detail/resources/tableData/instance/Name.jsx

The Name component renders the hyperlink for an instance. It was trying to use
the identity store to retrieve an Identity, but it was never listening to the
store for changes.

Fix instance rows to have hyperlinks in project details

---

troposphere/static/js/components/admin/Emulate.jsx

When you try to emulate a user within the "Admin > Manage Users" view, you are incorrectly redirected to `.../application/admin/emulate/:username`. This is an invalid URL.
With this work, the expected URL `.../application/emulate/:username` is used.
The root cause here is that the HTML `<a>` is not wise to the `basename` for the application. We define a utility function, `createAppHref(...)` to provide a consistent way to append the `basename` onto the `href`. 
**Note:** it looks like _emulation_ within the "beta" environment might be broken. 
See also [ATMO-1990](https://pods.iplantcollaborative.org/jira/browse/ATMO-1990)

Problem: Emulate component is using the wrong URL 

---

troposphere/static/js/components/images/list/ImageListView.jsx

**Problem:**
Image search is really slow
**Solution:**
Don't make unnecessary queries
We were making so many queries that browser became backlogged on requests,
making search very slow.
Render must use getWhere (as opposed to fetchWhere), otherwise every render
results in a search query. That way fetching occurs after user has finished
typing their query, which is triggered by 500ms of no further input.
See  [awaitingTimeout](https://github.com/cyverse/troposphere/blob/1577344f1f26c6cf927bd9e8d96f5fedaebbcc21/troposphere/static/js/components/mixins/ComponentHandleInputWithDelay.js#L23-L25) and [callIfNotInterruptedAfter](https://github.com/cyverse/troposphere/blob/1577344f1f26c6cf927bd9e8d96f5fedaebbcc21/troposphere/static/js/components/mixins/ComponentHandleInputWithDelay.js#L27-L39)

Don't fetch images when the query changes in render

---

troposphere/static/js/components/common/ui/SelectMenu.jsx

**Problem:**
The instance launch wizard was rendering a select menu with an invalid property.
**Solution:**
Make the select menu more lenient.
**Explanation:**
Prior version of SelectMenu required a list prop. However, the instance wizard–which renders several –renders these views w/o any guarantee that lists exist yet (it doesn't wait for imageVersions to be loaded for example).

Make SelectMenu more lenient

---

troposphere/static/js/actions/InstanceActions.js
troposphere/static/js/actions/instance/launch.js
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/components/BasicInfoForm.jsx
troposphere/static/js/components/modals/instance/launch/components/InstanceLaunchFooter.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourcesForm.jsx

When we moved to the `api/v2/instances` endpoint for launching new instances, we introduced latency to the ProjectResources view from when the instance is launched & it appears in the view (so the modal closing, but the POST is still _pending_ and could be so for 90 or more seconds). 
I looked into mirroring the "pending" resource approaches that is used by Volumes. This approach does an _eager-add_ into a collection that is conditionally concatenated when `getVolumesFor(project)` is called. 
I did attempt this approach first. It did not appear that the view as receiving _updates_. I was somewhat concerned with introducing the manual handling of _pending_ models. I do have the rough changes for this stashed.
Alter the behavior of the modal to make the Instance create submission prior to …

Handle Instance Launch submission before closing modal

---

troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx

With the v27 release, we shifted how the Instance Launch Wizard Modal performing a "launch". The modal remains open until the launch is successful, or returns to a "launch-ready" form on-failure (to allow changes in Size or Provider). 
But, this means the an `onSuccess(...)` callback function is now passed into a Promise-context, within the action. 
We want to be cautious in when we call `hide(..)` on a modal since it can generate an uncaught exception. So, we use a document selector, by ID, to determine if a modal is _mounted_ and **visible** to the community member. If there are no children for `div#modal`, then we no there is not a mounted modal component. 
Tracked within Sentry as `issues/334233103`

Problem: Trying hide an unmounted modal component

---

troposphere/static/js/models/Instance.js

The error was that the `scripts.map(...)` was returns an undefined attribute from the boot script models. 
This work properly translates the list of attached scripts (boot script models) to a list of UUIDs when creating the `models/Instance` on `api/v2/instances`.

Problem: a list of "null" sent for scripts on launch

---

troposphere/static/js/actions/NullProjectActions.js
troposphere/static/js/actions/ProjectActions.js
troposphere/static/js/actions/volume/update.js
troposphere/static/js/components/common/EditableInputField.jsx
troposphere/static/js/components/dashboard/DashboardPage.jsx
troposphere/static/js/stores/BaseStore.js
troposphere/static/js/stores/ProjectVolumeStore.js

There are two issues with volumes in the v27 release. The first issue is that the name couldn't be changed (this has already been fixed in master, and brought in here as @9bc4c34). The second issue is that volumes couldn't be moved between projects. I'll describe the the latter below.
The api changed, and tropo didn't get updated properly. The old API required 2 patches one to remove the old project-volume pairing, and the next to add a new project-volume pairing. The new api requires a single patch with the new project. 
Perform a single update on api v2 resources. This affects instances and volumes.

Fix volume update issues (updating a project, updating a name)

---

troposphere/static/js/components/modals/instance/launch/components/AdvancedOptionsFooter.jsx
troposphere/static/js/components/modals/instance/launch/components/InstanceLaunchFooter.jsx

The `disabled` HTML attributes on an `<a>...</a>` does not deactivate or block an "onClick" from being received. For an onHover, we do see a "disable" indicator. However, a click in the first view of the `<InstanceLaunchWizardModal />` does generate an error. 
It looks like Chrome and other browser may be generous here [too, according to MDN `<a>` does not have `disabled` as an attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a).
<details>
http://recordit.co/6JbrJI2yhZ
http://recordit.co/k8MLBp46l7
</details>

Problem: "disabled" Advanced Options still calls "onClick" handler

---

.travis.yml

This fixes a permission issue, unrelated to our code in the build:
OSError: [Errno 13] Permission denied: '/usr/local/bin/easy_install'
Resolves: https://github.com/cyverse/troposphere/issues/702 
Thanks @xuhang57

Use older travis image

---

troposphere/static/js/components/Header.jsx

Solution: Logout of API and then redirect to UI-logout
(Note this is only a problem when using the OpenstackLoginBackend -- does not need to be 'hotfixed' for production servers.)

Problem: UI logout does not log user out of the API

---

extras/troposphere.uwsgi.ini.j2

Solution: Use `LOCAL_DEV: True` variable to enable uWSGI
`python-autoreload` feature.
- ~[ ] New test(s) included to reproduce the bug/verify the feature~
- ~[ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~
- ~[ ] New variables supported in Clank~
- ~[] New variables committed to secrets repos~

Problem: Manual uWSGI reload in dev environment - Nope

---

troposphere/static/js/components/admin/ImageRequest.jsx
troposphere/static/js/components/common/InstanceDetail.jsx
troposphere/static/js/components/common/InstanceHistorySection.jsx
troposphere/static/js/components/common/image_request/ImageMembership.jsx
troposphere/static/js/components/common/ui/CollapsibleOutput.jsx
troposphere/static/js/components/projects/resources/instance/details/InstanceDetailsView.jsx
troposphere/static/js/context.js

Solution: Show fault message (and traceback, if staff)
- Remove redundancy -- Use a common 'InstanceDetail' component for both 'historical' and 'active-and-in-a-project' instances.
- Create an InstanceStatusHistory table
- Add polish to the table:
- Include a refresh button
- Show additional traceback if staff user is viewing (Even when emulated!)
- Include 'hasEmulatedSession' in context based on template variables.

Problem: Not enough information is visible to users/staff when a VM reaches error/deploy_error/user_deploy_error

---

troposphere/static/js/components/dashboard/DashboardPage.jsx

This might be intentional (I am not sure), but we have `SizeStore` called twice in both `componentDidMount` and `componentWillUnmount`.
Please feel free to close this PR if that is indeed intentional. :) 
This solves: https://github.com/cyverse/troposphere/issues/705
Thanks
Lucas

Fix repeated SizeStore event

---

troposphere/management/commands/maintenance.py

This provide a Django command for starting and stopping maintenance.
The start operation of the maintenance command will ask for overrides to sensible defaults. These are used when creating an instance of a MaintenanceRecord.
The stop operation of the maintenance command will "end-date" any active MaintenanceRecords, with the current time (provided by django.utils.timezone.now()).
This is an initial version that is not 💯% robust; yet, covers most of the common situations when operating planned maintenances.
A "source" included version of this is slated for a pull request against Troposphere that would provide the exact same commons. This would avoid having to know the namespaces of various models when performing maintenance.
If accepted, this would warrant updating the Atmosphere Guides …

Provide convenience for starting/stopping maintenance

---

package.json

Solution: restrict the content-base for webpack-dev-server to serve _only the assets_.

Problem: webpack-dev-server sets content base of "Troposphere home"

---

troposphere/static/js/models/Instance.js

To see the integration link to Web Desktop, an instance detail view would require a refresh.
In other word, if you left an InstanceDetail page open while the instance-deployment progressed,  the link would not appear. This is particularly frustrated because an instance with the capability of Web Desktop would not be obvious to a community member. 
The fix is that when we fetch the latest metadata for an Instance model from the Cloud :cloud:, we need to make sure to `.set` the `"web_desktop"` capability flag:
- https://github.com/cyverse/troposphere/blob/v27/troposphere/static/js/models/Instance.js#L48-L57
See also [ATMO-1573](https://pods.iplantcollaborative.org/jira/browse/ATMO-1573).

Problem: Web Desktop integration link only appears after refresh

---

troposphere/static/js/components/images/ImageDetailsPage.jsx
troposphere/static/js/components/images/detail/ImageDetailsView.jsx
troposphere/static/js/components/images/detail/stats/ImageStatsView.jsx
troposphere/static/js/models/ImageMetrics.js
troposphere/static/js/public_site/bootstrapper.jsx

The `<ImageDetailsPage />` and `<ImageDetailsView />` did not handle the usage scenario for Public Image Catalog
Changes made in this pull request:
- Include PatternMatchStore in public site's `stores`
- Exclude PatternMatchStore from "ready to render" check
- Only attempt to show Image Stats when logged in (and, for staff only)
Relates to #706 work ...

Problem: ImageDetailPage won't load for Public Image Catalog

---

troposphere/static/js/components/projects/resources/instance/details/sections/details/CreatedFrom.jsx

- Safety-checks to avoid failing on bootable volumes.
- Future-FIXMEs added as a reminder to include additional support for bootable volumes.

Problem: Version of instance not visible after launch

---

troposphere/static/js/components/common/boot_script/CreateScript.jsx
troposphere/static/js/components/common/boot_script/EditScript.jsx
troposphere/static/js/components/modals/instance/launch/components/BootScriptOption.jsx
troposphere/static/js/components/modals/script/ScriptCreateModal.jsx
troposphere/static/js/components/settings/advanced/ScriptListView.jsx

Changes related to PR #703 caused an error when using the Advanced Options of Instance Launch Modal when trying to "Save and Add" a new script (Deployment Script, aka Boot Script).
The error was three fold:
- the new Deployment type value modeled in this.state
- no handler for `onCreate` was passed, *required*
- no form-element present to choose Deployment type
This area is _hidden_ within the app, but is accessible via an hyperlink after an Image is selected.
To understand where the error is/was, here are step to reproduced:
- Go to Projects tab
- Select any Project
- Click "NEW > Instance"
- Select any Image
- Click on "Advanced Options" in bottom, left of modal
- Click on "Create a New Script"
This work resolves the issue and restores the expect flow for creating new scripts via this …

Problem: For Instance Launch, error(s) occur trying to "Save and Add Script"

---

troposphere/static/js/components/Master.jsx
troposphere/static/js/context.js

If we are emulating another community member, include the emulator and
a flag indicating that this is an emulated session.

Problem: Emulated sessions are not flagged for Sentry

---

troposphere/templates/no_user.html

The current "no account" page asks individuals to email Support. With the new Portal available, a more efficient request is to ask that they go to the User Portal. 
This leverages "Site Metadata" stored in Troposphere's database and is more available in a render context for templates via the following variables:
- `USER_PORTAL_LINK_TEXT`
- `USER_PORTAL_LINK`
These variables can be changed via the `tropo-admin/` page.
See also [ATMO-2076](https://pods.iplantcollaborative.org/jira/browse/ATMO-2076).
<details>
</details>

Problem: 'no account' suggests an inefficient action 

---

troposphere/static/js/components/modals/image_version/ImageVersionEditModal.jsx
troposphere/static/js/components/modals/image_version/membership/EditMembershipView.jsx

In beginning to look at implementing ATMO-1531 (associated a Document Object Identifier, DOI, with an Image Version), I noticed that `renderBody()` was handling the concerns of render 6 views associated with "Advanced Options". Along with the organization of function definitions. 
This uses the "[ExtractMethod](http://wiki.c2.com/?ExtractMethod)" refactor to pull out the work associated "Advanced Options" (along with dependent sub-views). 
This work also corrects issue with visual rendering of the form-group divisions. Several of these groups (End-date, and Minimum Requirements) were rendering below the horizontal rule (`<hr/>`) for the modal. Along with those corrections, the line-height for the inline buttons associated with the `<InteractiveDateField ... />` were adjusted to match the …

Problem: Edit ImageVersion Modal has become overgrown

---

troposphere/static/js/actions/ImageVersionLicenseActions.js

This fixes an error that occurs when trying to add a software license to an Image Version. 
There is no `license.uuid`, it's `undefined`. But the Model object has a `uuid` attribute that can be retrieved via `license.get("uuid")`. 
<details>
</details>

Problem: Cannot add a software license to a ImageVersion

---

troposphere/static/js/actions/ImageVersionLicenseActions.js
troposphere/static/js/components/images/detail/versions/Version.jsx
troposphere/static/js/components/images/detail/versions/VersionList.jsx
troposphere/static/js/components/modals/image_version/ImageVersionEditModal.jsx
troposphere/static/js/components/modals/image_version/doc_object_id/AddDocumentObjectIdentifier.jsx
troposphere/static/js/models/ImageVersion.js

Leverage API changes from: https://github.com/cyverse/atmosphere/pull/553
This allows a Document Object Identifier (DOI) issued by an external entity (Institution, Journal, etc) to be associated with a version of an Image within Atmosphere. 
This is done by editing the ImageVersion from the ImageDetail page (see details for screenshots). The interaction define by this pull request can be seen in an animated screen capture [here](http://recordit.co/3TIBiGLIvP). This includes resolving the DOI as a clickable hyperlink within the opened ImageVersion detail section.
See [ATMO-1531](https://pods.iplantcollaborative.org/jira/browse/ATMO-1531).
<details>
Associating a DOI with an ImageVersion is captured here: http://recordit.co/3TIBiGLIvP
The presence of a DOI on an ImageVersion is indicated by …

Problem: cannot associated DOI with Image Version

---

troposphere/static/js/components/admin/ResourceRequest/ResourceRequestView.jsx

This change affects the quota section under _Update the user's current resources_
Problem: The quota section contains providers that are no longer active
Solution: Filter the section to remove inactive providers

Filter quota section to only show active identities

---

troposphere/static/js/actions/HelpActions.js

Problem: attempt at removing RT from resource request approval was too ambitious
Solution: send resource requests to RT
We are going to continue sending resource requests to RT until the admin
resource request view is a closer replacement. Right now there's no way to
view closed requests and no way to reach out to the user for clarification.
This reverts commit acbf080.
Dependent pr https://github.com/cyverse/atmosphere/pull/555

Revert "Remove the admin_url, which is no longer included"

---

troposphere/static/js/components/admin/ResourceRequest/ResourceRequest.jsx

When an admin would save a quota in the admin resource request view, the save would fail.
Pass a username query paramater in the url
When the admin clicked 'save', a patch was submitted to /api/v2/identities/<id>. The response was a 404.
Normally that endpoint only operates the current user's identities. Any attempt to request or update another users' identities returns a 404. The current atmosphere implementation expected a query param to be passed: `username`. This signals the api to know that a user (must be an admin) wishes to updates models they don't own.
Because bunching all this functionality into a single end-point doesn't jive with our models/stores. We created api/v2/admin/<model> endpoints so that queryparams don't result in completely different behavior. This hotfix is …

Fix admin cannot update another user's identity

---

troposphere/static/js/AppRoutes.jsx
troposphere/static/js/components/common/InstanceDetail.jsx
troposphere/static/js/components/projects/InstanceDetailsPage.jsx
troposphere/static/js/components/projects/resources/instance/details/InstanceDetailsView.jsx

When you try to view an Instance that is still "available" in the cloud ☁️, the rendering will fail.
Solution - ensure that Instances have render-able, viewable details regardless of the 'path' to viewing. 
The `<InstanceDetail />` component is used in two contexts:
1. as part of Project context views, for "available", non-end_dated instances 
2. as part of Instance History, where instance might be "historic" or available
Let's define some terms in case you're confused!
An `"available"` instance is one that is not deleted. Since we do *not* _delete_ things in Atmosphere, we could also say that there is no "End Date" present. 
An `"historic"` instance is one that has been run, and then "end-dated" (aka deleted, or - if you want to be all cloud-y ☁️ "terminated"). 
An "available" instance …

Problem: In Instance History, Instances still "available" do not render detail

---

troposphere/static/js/components/settings/advanced/SSHConfiguration.jsx

I thought it would be nice to make the "more info" expansion symmetric. If you do not think it's nice, then I'll just close this and move on.

Problem: no way to close the "more info" section in SSH Configuration

---

troposphere/static/js/components/common/boot_script/EditScript.jsx
troposphere/static/js/components/settings/advanced/ScriptListView.jsx

This pull requests makes the suggested changes (in ATMO-2071) while including some extra information to make it slightly more clear that the options means. 
This work does not make the Script URL visible unless you click to edit the script.
See also [ATMO-2071](https://pods.iplantcollaborative.org/jira/browse/ATMO-2071)
<details>
An example interaction can be seen here: http://recordit.co/jFca5tAtcB
</details>

Problem: terminology/display labels inconsistent for Deployment Scripts

---

troposphere/static/js/components/admin/ImageMaster.jsx
troposphere/static/js/components/admin/ImageRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequestView.jsx

Add a close button so admins can close MachineRequests and Resource Requests

Allow closing of resource and image requests

---

troposphere/static/js/components/admin/ResourceRequest/ConfirmApproveModal.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequest.jsx
troposphere/static/js/components/admin/ResourceRequest/ResourceRequestView.jsx

Depends on https://github.com/cyverse/troposphere/pull/749
JIRA: [ATMO-2131](https://pods.iplantcollaborative.org/jira/browse/ATMO-2131)
Problem: Requests were being 'approved' while the resources were not being updated
Solution: Add a confirmation step/modal if resources havn't changed
This is a band-aid solution. Need to make the correct-flow obvious.

Add confirmation modal to admin resource request

---

troposphere/static/js/components/projects/detail/resources/InstanceActionButtons.jsx

This will show the "Unshelve" action for any "shelved_offloaded" instance within the ProjectDetails view. 
Not having this option present is likely why we get support questions about how to "fix" an instance in a "Shelved" state. 
<details>
</details>

Problem: shelved instances don't have unshelve action in button bar

---

CHANGELOG.md

Branch names (like v31) do not indicate a version frozen in time
Use tags which don't change (or shouldn't)

Identify a release with a tag, rather than branch whose reference changes

---

troposphere/static/js/models/ServerDeployVersion.js

Problem: the version reported for atmosphere ansible is invalid
Solution: return the correct endpoint

Fix the version resported for atmosphere-ansible

---

.travis.yml
troposphere/management/commands/maintenance.py
troposphere/management/commands/test_maintenance.py

The maintenance django command was changed in atmo/tropo. In atmo it was staged for v32, but it was staged for v33 in tropo. This brings the updated command into v32.

Bring new maitenance command into v32 release

---

CHANGELOG.md
troposphere/static/js/actions/NullProjectActions.js
troposphere/static/js/components/modals/nullProject/NullProjectMigrateResourceModal.jsx

During migrating resources modal, pick a default project for user
In the screenshot a default project is chosen, so I could migrate, by simple clicking one button. This will be helpful primarily to developers. If it were more helpful for users, i would consider looking into picking the last used project or something.

During migrating resources modal, pick a default project for user

---

CHANGELOG.md
troposphere/static/js/stores/ProviderStore.js

Launching an instance would result in an api error "No boot source exists for <uuid>"
Filter providers to those that have a non-enddated image version
An image has many versions, and each version has a provider machine, and each
machine can be enddated, which is how an image version can be disabled for a
provider.
We were populating the list of providers with any provider with an image
version, rather than any provider with a non-enddated version.

Fix incorrect  provider list in launch modal

---

CHANGELOG.md
troposphere/static/js/actions/ProfileActions.js
troposphere/static/js/components/settings/SettingsPage.jsx
troposphere/static/js/stores/ProfileStore.js

This allows users to have a nice experience in changing settings even when the API is slow.
If the requested changes fail to update in the API, the original settings will be restored in the interface and the user notified. The user is also notified on success.
Before this PR, users would click a new preference and nothing would happen for up to up to 6 seconds depending on the response from the API, causing them to rapidly click until the change finished.
Almost forgot to mention big thanks to @cdosborn for all the help with the PR including doing most of it and teaching me about React!

Enable optimistic updating in the Settings page

---

CHANGELOG.md
troposphere/static/js/components/modals/project/ProjectDeleteConditionsModal.jsx
troposphere/static/js/components/projects/common/SecondaryProjectNavigation.jsx

A user who wants to delete a project has to delete unnecessary resources like linked applications/urls in the project
Only prohibit deletion if active instances/volumes are present
Related: https://github.com/cyverse/atmosphere/pull/640

Allow project delete if instances/volumes are removed

---

PULL_REQUEST_TEMPLATE.md

Adding clank secrets should be a part of clank's PR process not tropospheres

Remove redundant todo item

---

CHANGELOG.md
dev_requirements.txt
requirements.in
requirements.txt

This PR updates the requirements to make Troposphere run on Ubuntu 18.04.
The **only** change between 2.7.3 and 2.7.3.1 is a bug fix that prevents
a glibc incompatibility on Ubuntu 16+
This is required for PRs:
- Atmosphere [PR #696](https://github.com/cyverse/atmosphere/pull/696)
- Clank [PR #283](https://github.com/cyverse/clank/pull/283)

Update requirements to use psycopg 2.7.3.1

---

troposphere/static/js/components/common/ui/CollapsibleOutput.jsx

An error output can be reveled by clicking on an ellipsis, however when a user clicks on the code block to copy the text, the code block is closed before the contents can be selected.
This PR moves the handler to the ellipsis so that the ellipses must be clicked to close the code block. It addition, for convenience, a quick copy button was added. 
Go to `./admin/imaging-requests` and find an image request with "(ERROR) next to the name. in the list on the left. click on it to view its details and find "Request state" and the ellipsis button in question to the right.

JETSTREAM-208: Don't close code block when clicked

---

troposphere/static/js/components/modals/instance/InstanceShelveModal.jsx
troposphere/static/js/components/modals/instance/InstanceStopModal.jsx
troposphere/static/js/components/modals/instance/InstanceSuspendModal.jsx
troposphere/static/js/components/modals/instance/components/AttachedVolumeWarning.jsx
troposphere/static/js/modals/instance/shelve.js
troposphere/static/js/modals/instance/stop.js
troposphere/static/js/modals/instance/suspend.js

If a volume is attached add alert message to modals Suspend, Stop, and Shelve informing the user that they must first detach the volume before performing the action.

JETSTREAM-215: Add volume attached alert to stop/suspend/shelve

---

troposphere/static/js/components/images/list/list/ImageCardList.jsx

When a user is an admin they will have a toggle on image lists that allows them to toggle showing or hiding end dated images

JETSTREAM-237: admins can toggle filtering end dated images

---

CHANGELOG.md
troposphere/static/js/components/modals/instance/InstanceImageWizardModal.jsx
troposphere/static/js/components/modals/instance/image/steps/ImageInfoStep.jsx

When a opens the Image Request Modal the basic info has an option to set tags. Tags from the base image should be added by default for the users convenience and a message states so. Instead there are no images added. This PR fixes that so the tag list is populated as expected.

ATMO-2143: Image Request not populating base image tags

---

CHANGELOG.md
troposphere/static/js/components/modals/instance/ExplainInstanceDeleteConditionsModal.jsx

The delete instance when volumes are attached warning message wasn't concise and the formatting was clunky. This PR improves the message and formatting.

Improve delete instance when volumes are attached warning message and format

---

CHANGELOG.md

This skips `v36-1` in order to match Atmosphere versions

Update CHANGELOG for v36-2

---

CHANGELOG.md
troposphere/static/js/actions/InstanceActions.js
troposphere/static/js/actions/instance/launch.js
troposphere/static/js/actions/instance/multiLaunch.js
troposphere/static/js/components/modals/instance/InstanceLaunchWizardModal.jsx
troposphere/static/js/components/modals/instance/launch/components/BasicInfoForm.jsx
troposphere/static/js/components/modals/instance/launch/components/ResourceGraphs.jsx
troposphere/static/js/models/Instance.js

Add a new field in the Launch Instance Wizard for number of instance to be launched, make use of the multi-instance-launch from Atmosphere

Multi instance launch
